In [1]:
file.create("hello.R") #create a file

[1] TRUE

In [2]:
print("hello, world")

[1] "hello, world"

In [3]:
name <- readline("What's your name:")
up_name <- paste("Hello,",name)
print(up_name)

What's your name: 5

[1] "Hello, 5"

In [4]:
name <- readline("What's your name:")
print(paste("Hello,",name))

What's your name: 5

[1] "Hello, 5"

In [5]:
paste('A','B','C',sep = "/")

[1] "A/B/C"

In [6]:
roy <- readline("Enter Vote for roy :")
sam <- readline("Enter Vote for roy :")
joy <- readline("Enter Vote for roy :")

roy <- as.integer(roy)
sam <- as.integer(sam)
joy <- as.integer(joy)

total = roy + sam + joy
print(paste("Total Votes is",total))

Enter Vote for roy : 5
Enter Vote for roy : 5
Enter Vote for roy : 6

[1] "Total Votes is 16"

In [7]:
roy <- as.integer( readline("Enter Vote for roy :") )
sam <- as.integer( readline("Enter Vote for roy :") )
joy <- as.integer( readline("Enter Vote for roy :") )

total = sum(roy, sam, joy)
print(paste("Total Votes is",total))

Enter Vote for roy : 56
Enter Vote for roy : 656
Enter Vote for roy : 56

[1] "Total Votes is 768"

In [8]:
votes <- read.csv("votes.csv")

Warning message in read.table(file = file, header = header, sep = sep, quote = quote, :
"incomplete final line found by readTableHeader on 'votes.csv'"

In [9]:
View(votes)

  candidate poll mail
1 Mario     37    63
2 Peach     43   107
3 Bowser    84    36

In [10]:
votes[]
votes[1,1]
votes[,2] #[row ,column]
votes[3,]
votes[2,2]

  candidate poll mail
1 Mario     37    63
2 Peach     43   107
3 Bowser    84    36

[1] "Mario"

[1] 37 43 84

  candidate poll mail
3 Bowser    84   36

[1] 43

In [11]:
votes$poll
votes$mail #dataframe$colunm

[1] 37 43 84

[1]  63 107  36

In [12]:
votes$candidate[2]

[1] "Peach"

In [13]:
sum(votes$poll[1] , votes$poll[2] , votes$poll[3])

[1] 164

In [14]:
sum(votes$poll)

[1] 164

In [15]:
sum(votes$mail)

[1] 206

In [16]:
votes$mail + votes$poll

[1] 100 150 120

In [17]:
votes$total <- votes$mail + votes$poll

In [18]:
votes

  candidate poll mail total
1 Mario     37    63  100
2 Peach     43   107  150
3 Bowser    84    36  120

In [19]:
write.csv(votes,"Update.csv")

In [20]:
colnames(votes)
rownames(votes)

[1] "candidate" "poll"      "mail"      "total"

[1] "1" "2" "3"

In [21]:
url <- "https://github.com/fivethirtyeight/data/raw/master/non-voters/nonvoters_data.csv"
voters <- read.csv(url)

In [22]:
View(voters)

     RespId weight Q1 Q2_1 Q2_2 Q2_3 Q2_4 Q2_5 Q2_6 Q2_7 ⋯ Q30 Q31 Q32 Q33
1    470001 0.7516 1  1    1     2    4   1    4    2    ⋯ 2   NA   1  NA
2    470002 1.0267 1  1    2     2    3   1    1    2    ⋯ 3   NA  NA   1
3    470003 1.0844 1  1    1     2    2   1    1    2    ⋯ 2   NA   2  NA
4    470007 0.6817 1  1    1     1    3   1    1    1    ⋯ 2   NA   1  NA
5    480008 0.9910 1  1    1    -1    1   1    1    1    ⋯ 1   -1  NA  NA
6    480009 1.0591 1  3    2     3    4   1    3    3    ⋯ 5   NA  NA  -1
7    480010 1.1512 1  1    1     2    3   1    1    1    ⋯ 1    1  NA  NA
8    470008 1.0174 1  1    1     2    2   1    3    1    ⋯ 2   NA   1  NA
9    470010 0.8184 1  1    1     1    3   1    1    1    ⋯ 1    1  NA  NA
10   470011 1.1653 1  1    1     2    1   1    1    1    ⋯ 3   NA  NA   1
11   470013 0.9517 1  1    2     2    2   2    2    2    ⋯ 1    1  NA  NA
12   470016 1.3740 1  1    1     1    4   1    4    2    ⋯ 2   NA   1  NA
13   480020 0.8438 1  3    4     2    2   4    2    1    ⋯ 1    2  NA  NA
14   470017 1.2745 1  1    1     3    3   1    1    1    ⋯ 5   NA  NA   1
15   470018 0.9742 1  1    1     1    1   1    1    1    ⋯ 1    1  NA  NA
16   470019 0.9893 1  1    1     1    1   1    1    1    ⋯ 1    1  NA  NA
17   470022 0.8473 1  1    1     1    1   1    1    1    ⋯ 2   NA   1  NA
18   470025 1.1030 1  1    1     1    1   1    1    1    ⋯ 1    1  NA  NA
19   470027 0.9687 1  1    1     1    2   1    2    1    ⋯ 5   NA  NA   1
20   470028 0.8401 1  1    1     1    1   1    1    1    ⋯ 5   NA  NA   2
21   470029 1.0167 1  2    3     3    2   1    3    1    ⋯ 5   NA  NA   1
22   470030 0.9067 1  1    1     2    1   1    1    1    ⋯ 1    2  NA  NA
23   470031 0.3353 1  1    1     2    2   1    3    1    ⋯ 3   NA  NA   2
24   470033 1.1927 1  1    1     1    1   1    1    1    ⋯ 3   NA  NA   1
25   470034 1.0560 1  1    1     1    1   1    1    1    ⋯ 1    1  NA  NA
26   470035 0.9261 1  1    2     1    4   1    4    3    ⋯ 2   NA   1  NA
27   470036 0.9840 1  2    2     2    3   1    3    2    ⋯ 2   NA   2  NA
28   470037 1.0533 1  1    2     2    1   1    1    1    ⋯ 3   NA  NA   1
29   470038 0.7479 1  1    1    -1   -1   1    1    1    ⋯ 1    1  NA  NA
30   470039 0.9261 1  1    1     1    3   1    1    1    ⋯ 1    1  NA  NA
⋮    ⋮      ⋮      ⋮  ⋮    ⋮    ⋮    ⋮    ⋮    ⋮    ⋮    ⋱ ⋮   ⋮   ⋮   ⋮
5807 477626 1.1907 1  3    3    2    2    2    1    2    ⋯ 3   NA  NA   1
5808 477629 0.7182 1  1    1    1    2    1    3    1    ⋯ 3   NA  NA   2
5809 477630 0.8081 1  1    2    2    3    1    1    1    ⋯ 5   NA  NA   2
5810 477631 0.8044 1  1    2    1    3    1    3    1    ⋯ 3   NA  NA   2
5811 477632 1.2926 1  1    1    2    1    2    1    1    ⋯ 1    1  NA  NA
5812 477633 1.6218 1  1    1    1    2    1    1    1    ⋯ 5   NA  NA   2
5813 477634 0.8961 1  1    2    1    2    1    2    1    ⋯ 3   NA  NA   1
5814 477635 1.3618 1  2    2    2    2    2    1    1    ⋯ 5   NA  NA   2
5815 477637 0.9726 1  1    1    2    2    1    1    1    ⋯ 1    2  NA  NA
5816 477638 1.0894 1  1    1    2    1    1    2    1    ⋯ 3   NA  NA   1
5817 477639 1.1379 1  1    2    2    1    1    1    1    ⋯ 1    1  NA  NA
5818 477640 2.0268 1  3    2    2    2    3    1    2    ⋯ 1    2  NA  NA
5819 477644 0.8133 1  1    4    3    4    1    2    2    ⋯ 2   NA   2  NA
5820 477646 0.8741 1  1    2    1    1    1    1    1    ⋯ 2   NA   2  NA
5821 477647 1.1846 1  1    1    1    3    1    1    1    ⋯ 3   NA  NA   2
5822 477648 1.2745 1  1    1    1    2    1    1    1    ⋯ 1    1  NA  NA
5823 477649 1.1198 1  1    2    2    1    1    1    1    ⋯ 1    1  NA  NA
5824 477650 0.7646 1  1    2    1    3    2    3    2    ⋯ 3   NA  NA   1
5825 477651 1.0111 1  4    3    4    4    4    4    4    ⋯ 5   NA  NA   2
5826 477653 0.8688 1  2    3    1    4    1    4    3    ⋯ 3   NA  NA   2
5827 477654 0.7655 1  1    1    1    2    1    1    1    ⋯ 3   NA  NA   2
5828 477657 1.5600 1  1    1    1    1    1    1    1    ⋯ 1    1  NA  NA
5829 477658 1.3218 1  1    1    2    4    2    4    2    ⋯ 4   NA  NA   1
5830 477660 1.2671 1  2    1    2    1    1    2    1    ⋯ 2   NA   2  NA
5831 477661 1.2518 1  1    2    1    2    2    1    1    ⋯ 5   NA  NA   2
5832 477662 1.1916 1  1    3    1    3    1    2    2    ⋯ 2   NA   1  NA
5833 477663 1.4623 1  1    1    1    2    1    2    1    ⋯ 2   NA   2  NA
5834 488322 0.9252 1  1    2    1    3    1    1    2    ⋯ 2   NA   1  NA
5835 488325 2.6311 1  2    2    2    2    2    2    2    ⋯ 3   NA  NA   1
5836 477666 1.6218 1  1    3    2    3    1    1    2    ⋯ 5   NA  NA   2
     ppage educ                race        gender income_cat     voter_category
1    73    College             White       Female $75-125k       always
2    90    College             White       Female $125k or more  always
3    53    College             White       Male   $125k or more  sporadic
4    58    Some college        Black       Female $40-75k        sporadic
5    81    High school or less White       Male   $40-75k        always
6    61    High school or less White       Female $40-75k        rarely/never
7    80    High school or less White       Female $125k or more  always
8    68    Some college        Other/Mixed Female $75-125k       always
9    70    College             White       Male   $125k or more  always
10   83    Some college        White       Male   $125k or more  always
11   43    College             White       Male   $75-125k       sporadic
12   42    College             White       Female $125k or more  sporadic
13   48    College             White       Male   $40-75k        rarely/never
14   52    Some college        White       Male   $125k or more  sporadic
15   80    High school or less White       Female $40-75k        always
16   76    High school or less White       Female $75-125k       sporadic
17   73    Some college        White       Female Less than $40k always
18   52    College             White       Female $125k or more  always
19   63    Some college        White       Male   $75-125k       always
20   81    Some college        White       Male   Less than $40k always
21   46    Some college        Other/Mixed Male   Less than $40k rarely/never
22   62    Some college        White       Male   $40-75k        always
23   62    College             Black       Male   $75-125k       sporadic
24   84    High school or less White       Male   Less than $40k sporadic
25   53    College             White       Female $75-125k       sporadic
26   71    High school or less White       Female Less than $40k always
27   50    High school or less Black       Female Less than $40k rarely/never
28   77    Some college        White       Female $75-125k       sporadic
29   67    College             White       Male   $40-75k        always
30   80    High school or less White       Female Less than $40k always
⋮    ⋮     ⋮                   ⋮           ⋮      ⋮              ⋮
5807 36    High school or less White       Male   $75-125k       rarely/never
5808 28    College             Hispanic    Male   $75-125k       sporadic
5809 54    Some college        Hispanic    Female $125k or more  sporadic
5810 73    College             White       Male   $125k or more  sporadic
5811 23    Some college        White       Female $40-75k        always
5812 26    High school or less Black       Female Less than $40k rarely/never
5813 61    High school or less White       Male   Less than $40k sporadic
5814 39    High school or less White       Female Less than $40k sporadic
5815 40    College             Other/Mixed Male   $125k or more  sporadic
5816 41    Some college        White       Male   $75-125k       sporadic
5817 44    Some college        White       Male   $75-125k       rarely/never
5818 34    High school or less White       Male   Less than $40k rarely/never
5819 29    College             Hispanic    Male   $40-75k        sporadic
5820 70    Some college        White       Male   $75-125k       always
5821 32    Some college        Other/Mixed Female $40-75k        sporadic
5822 55    Some college        White       Male   $125k or more  sporadic
5823 56    Some college        White       Female $75-125k       sporadic
5824 36    Some college        Hispanic    Female $40-75k        rarely/never
5825 59    High school or less Hispanic    Male   $75-125k       sporadic
5826 23    College             White       Female Less than $40k rarely/never
5827 47    High school or less Hispanic    Male   $40-75k        sporadic
5828 45    Some college        White       Female $125k or more  sporadic
5829 37    Some college        White       Female $40-75k        sporadic
5830 33    High school or less Black       Female Less than $40k rarely/never
5831 26    High school or less White       Female $75-125k       rarely/never
5832 27    Some college        Hispanic    Male   $40-75k        always
5833 59    High school or less White       Female $125k or more  rarely/never
5834 51    College             Other/Mixed Male   $125k or more  sporadic
5835 22    High school or less Black       Female Less than $40k always
5836 22    High school or less Black       Female Less than $40k always

In [23]:
nrow(voters)

[1] 5836

In [24]:
ncol(voters)

[1] 119

In [25]:
voters$voter_category

   [1] "always"       "always"       "sporadic"     "sporadic"
   [5] "always"       "rarely/never" "always"       "always"
   [9] "always"       "always"       "sporadic"     "sporadic"
  [13] "rarely/never" "sporadic"     "always"       "sporadic"
  [17] "always"       "always"       "always"       "always"
  [21] "rarely/never" "always"       "sporadic"     "sporadic"
  [25] "sporadic"     "always"       "rarely/never" "sporadic"
  [29] "always"       "always"       "always"       "always"
  [33] "rarely/never" "always"       "sporadic"     "sporadic"
  [37] "sporadic"     "sporadic"     "always"       "sporadic"
  [41] "rarely/never" "sporadic"     "always"       "always"
  [45] "always"       "always"       "always"       "always"
  [49] "always"       "always"       "sporadic"     "sporadic"
  [53] "always"       "sporadic"     "sporadic"     "always"
  [57] "sporadic"     "always"       "always"       "always"
  [61] "rarely/never" "always"       "rarely/never" "sporadic"
  [65] "rarely/never" "sporadic"     "rarely/never" "rarely/never"
  [69] "rarely/never" "always"       "sporadic"     "sporadic"
  [73] "rarely/never" "sporadic"     "rarely/never" "rarely/never"
  [77] "sporadic"     "always"       "rarely/never" "rarely/never"
  [81] "sporadic"     "rarely/never" "always"       "rarely/never"
  [85] "always"       "always"       "sporadic"     "always"
  [89] "sporadic"     "always"       "always"       "sporadic"
  [93] "always"       "sporadic"     "always"       "always"
  [97] "rarely/never" "rarely/never" "rarely/never" "always"
 [101] "rarely/never" "sporadic"     "rarely/never" "always"
 [105] "always"       "sporadic"     "sporadic"     "always"
 [109] "sporadic"     "sporadic"     "sporadic"     "sporadic"
 [113] "sporadic"     "always"       "always"       "always"
 [117] "always"       "always"       "always"       "always"
 [121] "sporadic"     "sporadic"     "sporadic"     "rarely/never"
 [125] "always"       "sporadic"     "always"       "sporadic"
 [129] "always"       "rarely/never" "always"       "rarely/never"
 [133] "rarely/never" "always"       "always"       "sporadic"
 [137] "sporadic"     "always"       "always"       "sporadic"
 [141] "always"       "always"       "always"       "rarely/never"
 [145] "always"       "always"       "always"       "sporadic"
 [149] "sporadic"     "sporadic"     "rarely/never" "sporadic"
 [153] "always"       "always"       "always"       "rarely/never"
 [157] "always"       "sporadic"     "sporadic"     "sporadic"
 [161] "sporadic"     "always"       "always"       "rarely/never"
 [165] "sporadic"     "sporadic"     "sporadic"     "sporadic"
 [169] "sporadic"     "always"       "always"       "rarely/never"
 [173] "rarely/never" "sporadic"     "rarely/never" "rarely/never"
 [177] "sporadic"     "rarely/never" "always"       "always"
 [181] "sporadic"     "always"       "sporadic"     "always"
 [185] "sporadic"     "sporadic"     "always"       "always"
 [189] "always"       "always"       "sporadic"     "always"
 [193] "always"       "sporadic"     "sporadic"     "always"
 [197] "sporadic"     "sporadic"     "sporadic"     "always"
 [201] "rarely/never" "always"       "always"       "rarely/never"
 [205] "sporadic"     "always"       "always"       "rarely/never"
 [209] "rarely/never" "rarely/never" "always"       "sporadic"
 [213] "sporadic"     "sporadic"     "sporadic"     "always"
 [217] "sporadic"     "always"       "sporadic"     "sporadic"
 [221] "always"       "always"       "sporadic"     "always"
 [225] "sporadic"     "always"       "always"       "rarely/never"
 [229] "always"       "sporadic"     "rarely/never" "sporadic"
 [233] "sporadic"     "sporadic"     "always"       "sporadic"
 [237] "sporadic"     "sporadic"     "always"       "sporadic"
 [241] "always"       "rarely/never" "sporadic"     "always"
 [245] "always"       "sporadic"     "rarely/never" "always"
 [249] "sporadic"     "always"       "sporadic"     "always"
 [253] "sporadic"     "sporadic"     "sporadic"     "always"
 [257] "always"       "rarely/never" "rarely/never" "always"
 [261] "always"       "sporadic"     "rarely/never" "sporadic"
 [265] "sporadic"     "always"       "sporadic"     "rarely/never"
 [269] "sporadic"     "sporadic"     "sporadic"     "rarely/never"
 [273] "always"       "always"       "always"       "rarely/never"
 [277] "rarely/never" "sporadic"     "sporadic"     "always"
 [281] "sporadic"     "sporadic"     "always"       "always"
 [285] "rarely/never" "always"       "sporadic"     "rarely/never"
 [289] "always"       "always"       "sporadic"     "always"
 [293] "always"       "always"       "always"       "sporadic"
 [297] "always"       "always"       "always"       "rarely/never"
 [301] "always"       "rarely/never" "sporadic"     "sporadic"
 [305] "always"       "always"       "sporadic"     "always"
 [309] "sporadic"     "sporadic"     "rarely/never" "sporadic"
 [313] "sporadic"     "always"       "sporadic"     "always"
 [317] "always"       "sporadic"     "sporadic"     "always"
 [321] "always"       "rarely/never" "sporadic"     "always"
 [325] "always"       "sporadic"     "sporadic"     "always"
 [329] "sporadic"     "rarely/never" "always"       "sporadic"
 [333] "sporadic"     "rarely/never" "sporadic"     "sporadic"
 [337] "always"       "sporadic"     "sporadic"     "sporadic"
 [341] "sporadic"     "always"       "sporadic"     "sporadic"
 [345] "sporadic"     "always"       "always"       "always"
 [349] "sporadic"     "sporadic"     "always"       "sporadic"
 [353] "always"       "always"       "rarely/never" "always"
 [357] "sporadic"     "sporadic"     "sporadic"     "rarely/never"
 [361] "always"       "always"       "sporadic"     "always"
 [365] "sporadic"     "sporadic"     "sporadic"     "always"
 [369] "sporadic"     "always"       "sporadic"     "sporadic"
 [373] "always"       "always"       "sporadic"     "always"
 [377] "always"       "always"       "rarely/never" "always"
 [381] "always"       "always"       "always"       "always"
 [385] "always"       "rarely/never" "sporadic"     "sporadic"
 [389] "always"       "always"       "sporadic"     "always"
 [393] "always"       "always"       "sporadic"     "always"
 [397] "rarely/never" "sporadic"     "sporadic"     "always"
 [401] "sporadic"     "sporadic"     "always"       "sporadic"
 [405] "sporadic"     "rarely/never" "always"       "always"
 [409] "sporadic"     "always"       "always"       "sporadic"
 [413] "always"       "always"       "always"       "rarely/never"
 [417] "sporadic"     "rarely/never" "sporadic"     "rarely/never"
 [421] "sporadic"     "rarely/never" "always"       "always"
 [425] "rarely/never" "rarely/never" "sporadic"     "always"
 [429] "sporadic"     "always"       "sporadic"     "always"
 [433] "rarely/never" "sporadic"     "sporadic"     "always"
 [437] "always"       "always"       "sporadic"     "sporadic"
 [441] "always"       "always"       "always"       "always"
 [445] "rarely/never" "always"       "always"       "always"
 [449] "sporadic"     "rarely/never" "always"       "always"
 [453] "sporadic"     "rarely/never" "sporadic"     "always"
 [457] "sporadic"     "always"       "sporadic"     "always"
 [461] "sporadic"     "always"       "sporadic"     "rarely/never"
 [465] "always"       "always"       "sporadic"     "sporadic"
 [469] "sporadic"     "always"       "always"       "always"
 [473] "always"       "always"       "sporadic"     "always"
 [477] "always"       "always"       "always"       "always"
 [481] "rarely/never" "sporadic"     "rarely/never" "sporadic"
 [485] "rarely/never" "sporadic"     "sporadic"     "sporadic"
 [489] "always"       "sporadic"     "always"       "rarely/never"
 [493] "always"       "always"       "always"       "sporadic"
 [497] "sporadic"     "always"       "sporadic"     "always"
 [501] "sporadic"     "sporadic"     "rarely/never" "always"
 [505] "always"       "rarely/never" "always"       "always"
 [509] "always"       "always"       "always"       "sporadic"
 [513] "always"       "sporadic"     "rarely/never" "rarely/never"
 [517] "sporadic"     "always"       "sporadic"     "always"
 [521] "sporadic"     "always"       "sporadic"     "sporadic"
 [525] "always"       "always"       "sporadic"     "always"
 [529] "sporadic"     "always"       "sporadic"     "always"
 [533] "always"       "always"       "sporadic"     "always"
 [537] "always"       "always"       "always"       "sporadic"
 [541] "always"       "always"       "always"       "sporadic"
 [545] "rarely/never" "sporadic"     "always"       "sporadic"
 [549] "always"       "always"       "sporadic"     "always"
 [553] "sporadic"     "rarely/never" "sporadic"     "always"
 [557] "always"       "sporadic"     "always"       "always"
 [561] "rarely/never" "sporadic"     "sporadic"     "always"
 [565] "sporadic"     "always"       "sporadic"     "sporadic"
 [569] "sporadic"     "always"       "always"       "always"
 [573] "always"       "sporadic"     "always"       "sporadic"
 [577] "always"       "rarely/never" "always"       "rarely/never"
 [581] "always"       "always"       "always"       "always"
 [585] "always"       "always"       "rarely/never" "always"
 [589] "sporadic"     "sporadic"     "rarely/never" "rarely/never"
 [593] "sporadic"     "sporadic"     "sporadic"     "sporadic"
 [597] "always"       "sporadic"     "sporadic"     "always"
 [601] "sporadic"     "rarely/never" "rarely/never" "sporadic"
 [605] "always"       "always"       "sporadic"     "always"
 [609] "sporadic"     "sporadic"     "sporadic"     "sporadic"
 [613] "always"       "always"       "sporadic"     "always"
 [617] "sporadic"     "rarely/never" "sporadic"     "always"
 [621] "sporadic"     "sporadic"     "always"       "always"
 [625] "always"       "always"       "always"       "sporadic"
 [629] "rarely/never" "sporadic"     "always"       "rarely/never"
 [633] "always"       "sporadic"     "sporadic"     "sporadic"
 [637] "always"       "sporadic"     "sporadic"     "always"
 [641] "always"       "always"       "sporadic"     "sporadic"
 [645] "sporadic"     "always"       "sporadic"     "sporadic"
 [649] "sporadic"     "always"       "always"       "sporadic"
 [653] "always"       "always"       "rarely/never" "sporadic"
 [657] "sporadic"     "sporadic"     "sporadic"     "always"
 [661] "always"       "sporadic"     "always"       "sporadic"
 [665] "always"       "always"       "always"       "sporadic"
 [669] "sporadic"     "rarely/never" "sporadic"     "sporadic"
 [673] "rarely/never" "sporadic"     "always"       "sporadic"
 [677] "sporadic"     "always"       "sporadic"     "always"
 [681] "always"       "always"       "always"       "always"
 [685] "always"       "sporadic"     "sporadic"     "always"
 [689] "always"       "always"       "sporadic"     "always"
 [693] "rarely/never" "always"       "always"       "sporadic"
 [697] "sporadic"     "rarely/never" "sporadic"     "sporadic"
 [701] "always"       "sporadic"     "always"       "always"
 [705] "always"       "always"       "always"       "always"
 [709] "sporadic"     "always"       "rarely/never" "sporadic"
 [713] "always"       "sporadic"     "always"       "sporadic"
 [717] "sporadic"     "always"       "always"       "always"
 [721] "sporadic"     "sporadic"     "always"       "rarely/never"
 [725] "sporadic"     "rarely/never" "always"       "sporadic"
 [729] "sporadic"     "sporadic"     "sporadic"     "rarely/never"
 [733] "sporadic"     "always"       "sporadic"     "always"
 [737] "sporadic"     "always"       "always"       "always"
 [741] "always"       "always"       "always"       "sporadic"
 [745] "sporadic"     "sporadic"     "always"       "sporadic"
 [749] "sporadic"     "rarely/never" "sporadic"     "sporadic"
 [753] "sporadic"     "sporadic"     "always"       "always"
 [757] "sporadic"     "rarely/never" "sporadic"     "always"
 [761] "always"       "sporadic"     "always"       "always"
 [765] "sporadic"     "always"       "sporadic"     "sporadic"
 [769] "rarely/never" "sporadic"     "sporadic"     "sporadic"
 [773] "always"       "always"       "always"       "always"
 [777] "sporadic"     "always"       "always"       "sporadic"
 [781] "always"       "always"       "sporadic"     "sporadic"
 [785] "always"       "sporadic"     "always"       "always"
 [789] "sporadic"     "sporadic"     "rarely/never" "always"
 [793] "always"       "always"       "sporadic"     "always"
 [797] "sporadic"     "always"       "rarely/never" "sporadic"
 [801] "always"       "sporadic"     "always"       "always"
 [805] "always"       "sporadic"     "sporadic"     "sporadic"
 [809] "always"       "sporadic"     "sporadic"     "rarely/never"
 [813] "rarely/never" "sporadic"     "sporadic"     "sporadic"
 [817] "always"       "rarely/never" "sporadic"     "sporadic"
 [821] "always"       "always"       "always"       "sporadic"
 [825] "sporadic"     "always"       "always"       "sporadic"
 [829] "sporadic"     "rarely/never" "sporadic"     "sporadic"
 [833] "sporadic"     "always"       "sporadic"     "always"
 [837] "always"       "always"       "always"       "sporadic"
 [841] "rarely/never" "always"       "always"       "sporadic"
 [845] "always"       "always"       "always"       "always"
 [849] "always"       "always"       "always"       "sporadic"
 [853] "sporadic"     "always"       "sporadic"     "always"
 [857] "always"       "always"       "sporadic"     "rarely/never"
 [861] "always"       "always"       "sporadic"     "sporadic"
 [865] "sporadic"     "sporadic"     "sporadic"     "always"
 [869] "always"       "always"       "sporadic"     "always"
 [873] "rarely/never" "always"       "rarely/never" "sporadic"
 [877] "always"       "sporadic"     "always"       "rarely/never"
 [881] "always"       "rarely/never" "always"       "always"
 [885] "always"       "sporadic"     "always"       "sporadic"
 [889] "sporadic"     "rarely/never" "sporadic"     "sporadic"
 [893] "sporadic"     "rarely/never" "always"       "rarely/never"
 [897] "always"       "always"       "sporadic"     "sporadic"
 [901] "sporadic"     "sporadic"     "always"       "sporadic"
 [905] "rarely/never" "always"       "sporadic"     "always"
 [909] "always"       "always"       "always"       "always"
 [913] "sporadic"     "always"       "always"       "sporadic"
 [917] "always"       "always"       "always"       "always"
 [921] "always"       "rarely/never" "always"       "sporadic"
 [925] "always"       "sporadic"     "always"       "always"
 [929] "sporadic"     "always"       "always"       "rarely/never"
 [933] "always"       "sporadic"     "always"       "sporadic"
 [937] "always"       "always"       "sporadic"     "always"
 [941] "always"       "always"       "always"       "always"
 [945] "rarely/never" "always"       "rarely/never" "always"
 [949] "rarely/never" "always"       "always"       "sporadic"
 [953] "sporadic"     "always"       "always"       "rarely/never"
 [957] "always"       "always"       "sporadic"     "always"
 [961] "always"       "sporadic"     "sporadic"     "sporadic"
 [965] "always"       "always"       "always"       "always"
 [969] "sporadic"     "always"       "sporadic"     "rarely/never"
 [973] "sporadic"     "always"       "sporadic"     "sporadic"
 [977] "always"       "sporadic"     "always"       "rarely/never"
 [981] "always"       "sporadic"     "sporadic"     "rarely/never"
 [985] "sporadic"     "always"       "sporadic"     "sporadic"
 [989] "sporadic"     "sporadic"     "always"       "rarely/never"
 [993] "always"       "always"       "sporadic"     "always"
 [997] "always"       "always"       "sporadic"     "always"
[1001] "always"       "sporadic"     "always"       "always"
[1005] "sporadic"     "always"       "always"       "rarely/never"
[1009] "always"       "sporadic"     "always"       "rarely/never"
[1013] "always"       "sporadic"     "always"       "sporadic"
[1017] "sporadic"     "always"       "always"       "always"
[1021] "sporadic"     "sporadic"     "sporadic"     "sporadic"
[1025] "sporadic"     "sporadic"     "rarely/never" "sporadic"
[1029] "always"       "always"       "always"       "sporadic"
[1033] "sporadic"     "sporadic"     "sporadic"     "rarely/never"
[1037] "sporadic"     "always"       "sporadic"     "always"
[1041] "rarely/never" "sporadic"     "always"       "sporadic"
[1045] "sporadic"     "always"       "rarely/never" "sporadic"
[1049] "always"       "rarely/never" "always"       "sporadic"
[1053] "always"       "sporadic"     "rarely/never" "always"
[1057] "sporadic"     "sporadic"     "sporadic"     "rarely/never"
[1061] "sporadic"     "rarely/never" "always"       "always"
[1065] "sporadic"     "sporadic"     "always"       "always"
[1069] "rarely/never" "sporadic"     "rarely/never" "always"
[1073] "sporadic"     "rarely/never" "always"       "always"
[1077] "sporadic"     "sporadic"     "sporadic"     "always"
[1081] "sporadic"     "sporadic"     "rarely/never" "always"
[1085] "always"       "rarely/never" "sporadic"     "always"
[1089] "always"       "sporadic"     "rarely/never" "sporadic"
[1093] "always"       "sporadic"     "always"       "always"
[1097] "sporadic"     "sporadic"     "always"       "rarely/never"
[1101] "sporadic"     "sporadic"     "always"       "always"
[1105] "sporadic"     "sporadic"     "always"       "always"
[1109] "sporadic"     "rarely/never" "rarely/never" "rarely/never"
[1113] "sporadic"     "always"       "sporadic"     "sporadic"
[1117] "sporadic"     "sporadic"     "sporadic"     "rarely/never"
[1121] "sporadic"     "sporadic"     "sporadic"     "always"
[1125] "sporadic"     "sporadic"     "sporadic"     "sporadic"
[1129] "always"       "sporadic"     "rarely/never" "sporadic"
[1133] "rarely/never" "sporadic"     "rarely/never" "sporadic"
[1137] "sporadic"     "sporadic"     "always"       "sporadic"
[1141] "rarely/never" "always"       "sporadic"     "always"
[1145] "sporadic"     "rarely/never" "always"       "sporadic"
[1149] "rarely/never" "sporadic"     "sporadic"     "always"
[1153] "sporadic"     "sporadic"     "rarely/never" "rarely/never"
[1157] "always"       "always"       "sporadic"     "always"
[1161] "sporadic"     "rarely/never" "sporadic"     "always"
[1165] "rarely/never" "rarely/never" "sporadic"     "sporadic"
[1169] "sporadic"     "sporadic"     "rarely/never" "sporadic"
[1173] "sporadic"     "always"       "sporadic"     "rarely/never"
[1177] "always"       "sporadic"     "sporadic"     "rarely/never"
[1181] "rarely/never" "sporadic"     "rarely/never" "sporadic"
[1185] "sporadic"     "rarely/never" "rarely/never" "rarely/never"
[1189] "sporadic"     "sporadic"     "always"       "sporadic"
[1193] "always"       "sporadic"     "sporadic"     "always"
[1197] "always"       "sporadic"     "rarely/never" "sporadic"
[1201] "rarely/never" "sporadic"     "sporadic"     "rarely/never"
[1205] "sporadic"     "always"       "rarely/never" "always"
[1209] "rarely/never" "rarely/never" "rarely/never" "rarely/never"
[1213] "sporadic"     "always"       "rarely/never" "always"
[1217] "sporadic"     "always"       "sporadic"     "sporadic"
[1221] "rarely/never" "sporadic"     "always"       "sporadic"
[1225] "sporadic"     "always"       "always"       "sporadic"
[1229] "sporadic"     "always"       "sporadic"     "sporadic"
[1233] "sporadic"     "always"       "sporadic"     "always"
[1237] "sporadic"     "always"       "sporadic"     "rarely/never"
[1241] "sporadic"     "always"       "sporadic"     "always"
[1245] "rarely/never" "rarely/never" "sporadic"     "sporadic"
[1249] "always"       "sporadic"     "always"       "sporadic"
[1253] "sporadic"     "sporadic"     "always"       "always"
[1257] "sporadic"     "rarely/never" "sporadic"     "sporadic"
[1261] "rarely/never" "sporadic"     "always"       "always"
[1265] "always"       "always"       "sporadic"     "sporadic"
[1269] "always"       "always"       "rarely/never" "always"

In [26]:
head( voters$voter_category )

[1] "always"       "always"       "sporadic"     "sporadic"     "always"
[6] "rarely/never"

In [27]:
unique(voters$voter_category )

[1] "always"       "sporadic"     "rarely/never"

In [28]:
voters$Q22

   [1] NA NA NA NA NA  7 NA NA NA NA NA NA  6 NA NA NA NA NA NA NA  2 NA NA NA
  [25] NA NA  6 NA NA NA NA NA NA NA NA NA NA NA NA NA  6 NA NA NA NA NA NA NA
  [49] NA NA NA NA NA NA NA NA NA NA NA NA NA NA -1 NA NA NA NA  7 NA NA NA NA
  [73] NA NA  1 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
  [97]  4 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
 [121] NA NA NA NA NA NA NA NA NA NA NA NA NA  4 NA NA NA NA NA NA NA NA NA  6
 [145] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  7 NA NA NA NA
 [169] NA NA NA NA NA NA  4  6 NA  1 NA NA NA NA NA NA NA NA NA NA NA NA NA NA
 [193] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  6 NA  4 NA NA NA NA NA NA
 [217] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
 [241] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
 [265] NA NA NA NA NA NA NA NA NA NA NA NA  7 NA NA NA NA NA NA NA NA NA NA NA
 [289] NA NA NA NA NA NA NA NA NA NA NA  4 NA NA NA NA NA NA NA NA NA NA NA NA
 [313] NA NA NA NA NA NA NA NA NA  4 NA NA NA NA NA NA NA NA NA NA NA NA NA NA
 [337] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
 [361] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  2 NA NA NA NA NA
 [385] NA -1 NA NA NA NA NA NA NA NA NA NA  4 NA NA NA NA NA NA NA NA NA NA NA
 [409] NA NA NA NA NA NA NA  6 NA NA NA NA NA  7 NA NA  7 NA NA NA NA NA NA NA
 [433] NA NA NA NA NA NA NA NA NA NA NA NA  7 NA NA NA NA NA NA NA NA NA NA NA
 [457] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
 [481]  6 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
 [505] NA  6 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
 [529] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
 [553] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
 [577] NA NA NA NA NA NA NA NA NA NA NA NA NA NA  7 NA NA NA NA NA NA NA NA NA
 [601] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  7 NA NA NA NA NA NA
 [625] NA NA NA NA NA NA NA  2 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
 [649] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  7 NA NA
 [673] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
 [697] NA  4 NA NA NA NA NA NA NA NA NA NA NA NA  4 NA NA NA NA NA NA NA NA NA
 [721] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
 [745] NA NA NA NA NA  2 NA NA NA NA NA NA NA  2 NA NA NA NA NA NA NA NA NA  2
 [769]  2 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
 [793] NA NA NA NA NA NA  5 NA NA NA NA NA NA NA NA NA NA NA NA NA  4 NA NA NA
 [817] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
 [841] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
 [865] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
 [889] NA  6 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
 [913] NA NA NA NA NA NA NA NA NA  7 NA NA NA NA NA NA NA NA NA NA NA NA NA NA
 [937] NA NA NA NA NA NA NA NA NA NA  5 NA NA NA NA NA NA NA NA NA NA NA NA NA
 [961] NA NA NA NA NA NA NA NA NA NA NA  6 NA NA NA NA NA NA NA NA NA NA NA NA
 [985] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[1009] NA NA NA  4 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[1033] NA NA NA NA NA NA NA NA  2 NA NA NA NA NA  2 NA NA  7 NA NA NA NA  2 NA
[1057] NA NA NA NA NA NA NA NA NA NA NA NA  6 NA  4 NA NA  2 NA NA NA NA NA NA
[1081] NA NA  4 NA NA NA NA NA NA NA  6 NA NA NA NA NA NA NA NA NA NA NA NA NA
[1105] NA NA NA NA NA  6  7 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[1129] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  7 NA  2  3 NA NA NA
[1153] NA NA NA NA NA NA NA NA NA  4 NA NA NA NA NA NA NA NA  2 NA NA NA NA NA
[1177] NA NA NA  4 NA NA NA NA NA NA  6 NA NA NA NA NA NA NA NA NA NA NA NA NA
[1201] NA NA NA NA NA NA  2 NA NA  6 -1  4 NA NA NA NA NA NA NA NA NA NA NA NA
[1225] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  4 NA NA NA
[1249] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[1273] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  2
[1297]  6 NA NA NA NA NA NA  6 NA NA NA NA NA NA NA NA NA NA NA NA  6 NA NA NA
[1321] NA NA  4 NA NA NA NA NA NA NA NA NA NA NA  6 NA NA NA NA  7 NA NA NA NA
[1345] NA -1 NA NA NA NA NA NA NA NA NA NA NA NA NA  2 NA NA NA  6 NA  2 NA NA
[1369] NA  2 NA NA  6 NA NA NA NA NA  2 NA NA NA NA NA NA NA NA NA NA NA NA NA
[1393] NA NA NA NA NA  1 NA NA NA NA  2 NA NA NA NA NA NA NA NA NA NA NA NA  6
[1417] NA NA NA NA NA NA  6 NA NA NA NA NA NA NA NA NA NA NA NA -1 NA NA NA NA
[1441]  2 NA NA NA NA NA NA  6 NA NA NA NA  2 NA NA NA NA NA NA NA NA NA  6 NA
[1465] NA NA  4 NA NA NA NA NA  7 NA NA NA NA NA NA NA NA NA NA  4 NA NA NA NA
[1489] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  1 NA NA NA
[1513] NA NA NA NA NA NA NA NA NA  4 NA  2 NA NA  7 NA NA NA NA NA NA NA NA NA
[1537] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[1561] NA NA  6 NA  4 NA NA NA NA NA NA NA NA NA NA NA NA  5 NA NA NA NA  7 NA
[1585] NA NA NA  6 NA NA  2 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[1609]  4 NA  7 NA NA NA NA  4 NA  7 NA NA NA NA  2 NA NA NA NA  1 NA NA NA NA
[1633] NA NA  2 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[1657]  6 NA NA NA NA NA  4 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[1681]  2 NA NA NA NA NA NA NA NA NA NA NA  7 NA NA  4 NA NA NA NA  4 NA NA NA
[1705] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[1729] NA NA NA  7 NA NA NA NA NA NA NA NA NA NA  6 NA NA NA NA NA NA NA NA NA
[1753] NA NA  2 NA  7 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  7 NA
[1777] NA NA NA NA NA -1 NA NA NA NA NA NA  2 NA NA NA NA NA NA NA NA NA NA NA
[1801] NA NA NA NA NA  4 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  6 NA NA
[1825] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  7 NA NA NA NA NA NA
[1849] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[1873] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[1897] NA NA NA NA NA NA NA NA NA  4 NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[1921] NA NA  2  2 NA NA NA NA NA NA NA NA NA  6 NA NA NA NA NA NA NA NA NA NA
[1945] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  3 NA NA NA NA NA
[1969] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  6 NA
[1993] NA  5 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[2017] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  7 NA NA NA NA NA NA  6 NA
[2041] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  7 NA NA  6 NA
[2065] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  5
[2089] NA NA NA  2 NA NA NA NA  3 NA NA NA NA NA  4 NA NA NA NA NA NA NA NA NA
[2113]  2 NA NA NA NA NA NA NA NA  6 NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[2137] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  6  4 NA -1 NA NA
[2161] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[2185] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  1 NA NA NA
[2209] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  4 NA NA
[2233] NA NA NA NA NA NA NA NA NA NA NA NA  2 NA NA NA NA NA NA NA NA NA NA NA
[2257] NA NA NA NA NA  7 NA NA NA NA  4 NA NA NA NA NA NA NA NA NA NA NA NA NA
[2281] NA NA NA NA NA NA NA NA NA NA NA  4 NA NA NA NA NA NA NA NA NA NA NA NA
[2305] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  2 NA NA  2 NA
[2329] NA NA NA NA NA  2 NA NA NA NA NA  2 NA NA NA NA NA NA NA NA NA NA NA NA
[2353] NA  2  7 NA NA NA NA NA NA NA -1 NA NA NA NA NA NA  4 NA NA NA NA  2 NA
[2377] NA NA NA NA  4 NA NA NA NA NA NA NA NA NA NA NA NA NA  3 NA NA NA  5  4
[2401]  3 NA NA NA  7 NA NA NA NA NA  7 NA NA NA NA NA NA NA NA NA NA NA NA NA
[2425] NA NA NA  6 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[2449] NA  6 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[2473]  4 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  6 NA NA
[2497] NA  4 NA NA NA NA NA  6  7 NA NA NA NA NA NA NA NA  6 NA  1 NA NA NA NA
[2521] NA NA NA NA NA  7 NA NA NA NA NA NA  7  2  7 NA NA NA NA NA NA NA NA NA
[2545] NA NA NA  7 NA NA NA NA NA NA NA NA NA NA NA NA  2 NA NA NA NA NA NA  6
[2569] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[2593] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  4 NA
[2617] NA NA NA NA  6  4 NA  6  5 NA NA NA NA NA NA NA NA NA NA NA NA  2  2 NA
[2641] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[2665] NA NA NA NA  5 NA NA NA NA NA NA NA NA NA NA NA NA NA NA  7 NA NA  1 NA
[2689] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[2713] NA NA NA NA  2 NA NA NA NA NA NA  6 NA NA NA NA NA NA NA  4 NA NA NA NA
[2737] NA  4 NA NA  4 NA NA  6 NA NA NA NA NA NA  7 NA NA NA NA NA NA NA NA NA
[2761] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  4 NA NA NA NA
[2785] NA NA NA  5 NA  7 NA NA NA NA NA  3 NA  6 NA NA NA NA NA NA NA NA NA NA
[2809] NA NA NA NA NA NA NA NA NA NA NA NA NA NA  6 NA NA NA NA NA NA NA NA NA
[2833] NA NA NA NA NA NA NA NA NA  6 NA NA NA NA NA NA NA  4  7 NA NA NA NA NA
[2857] NA NA  7 NA NA NA NA NA NA NA NA NA NA NA  6  4 NA NA  4 NA NA NA NA NA
[2881] NA NA NA NA NA NA NA  4 NA NA NA NA NA NA NA NA NA NA  2 NA NA NA NA NA
[2905]  6 NA NA NA NA NA NA  2 NA NA NA  6 NA NA NA  7 NA NA NA NA NA NA  4 NA
[2929] NA NA NA NA  2 NA NA NA NA NA NA NA NA NA NA  7 NA NA NA NA NA NA  7 NA
[2953] NA NA  4 NA NA NA NA NA NA  2 NA NA NA NA NA NA NA NA NA NA NA NA NA  4
[2977] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[3001] NA NA NA NA  4 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[3025] NA NA NA NA  6 NA NA NA NA NA  4  3 NA  4 NA NA NA NA  4 NA NA NA NA NA
[3049] NA NA NA  4 NA NA NA NA NA NA NA NA NA  7 NA NA NA NA NA NA NA NA NA NA
[3073] NA NA NA NA NA NA NA NA NA NA NA NA NA  1 NA NA NA NA NA NA NA NA NA NA
[3097] NA NA NA NA  2 NA NA NA NA NA NA NA NA NA NA NA  4 NA NA NA  2 NA NA NA
[3121] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  2 NA NA NA
[3145] NA NA NA NA NA NA NA NA  3 NA NA NA  1 NA  4 NA NA NA NA NA NA NA NA NA
[3169] NA NA NA NA NA  4 NA  4 NA NA NA  4 NA NA  2 NA  4 NA NA NA NA NA NA NA
[3193]  7 NA  7 NA NA NA NA NA NA NA NA  6  4 NA NA NA  3 NA NA NA  4 NA NA NA
[3217] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  6 NA NA NA
[3241] NA NA NA NA NA NA NA NA NA NA NA NA  6 NA NA NA NA NA NA NA NA  4 NA NA
[3265] NA NA  2 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  7 NA
[3289] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  2 NA NA NA NA
[3313] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  6  2 NA NA NA NA NA
[3337] NA NA  4 NA NA NA NA NA NA NA NA NA NA NA NA  7 NA NA NA NA NA NA  4 NA
[3361] NA NA NA NA  5 NA NA NA NA NA NA NA NA NA  2 NA NA NA NA NA NA NA NA NA
[3385] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  3 NA NA NA
[3409] NA NA NA NA NA NA NA  4 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[3433]  2 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[3457] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  4 NA NA NA NA NA NA NA NA
[3481] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[3505] NA NA NA NA NA  7 NA NA  6  7 NA NA NA NA NA  7 NA NA NA NA NA NA NA NA
[3529] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  6 NA NA NA NA NA NA
[3553] NA NA NA NA  6 NA NA NA  1 NA NA NA  1 NA NA NA NA NA NA NA  4 NA NA NA
[3577] NA NA NA NA NA NA NA NA NA NA  7 NA NA NA  7 NA NA NA NA NA NA NA NA NA
[3601] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  4 NA NA
[3625] NA NA NA  7  2 NA NA NA NA NA NA NA NA  6 NA NA NA NA NA NA NA NA NA NA
[3649] NA NA NA NA NA NA NA NA -1 NA  1 NA NA NA NA NA  6 NA NA NA NA NA NA NA
[3673] NA  2 NA NA NA NA NA NA NA NA NA NA NA  7 NA NA NA NA NA NA NA NA NA NA
[3697] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  7 NA NA  3  6 NA NA NA
[3721] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  2 NA NA NA NA NA NA NA NA
[3745] NA  2 NA NA NA NA NA NA NA NA NA NA NA NA  6 NA NA  4 NA NA NA NA NA NA
[3769] NA NA NA NA NA NA NA  6 NA NA  6 NA NA NA NA NA NA NA NA NA NA NA NA NA
[3793] NA NA NA NA NA NA NA NA NA  1 NA NA NA  3  5 NA NA NA NA NA NA  2 NA NA
[3817] NA NA NA NA NA NA NA NA  6 NA NA NA NA NA NA  7 NA NA NA NA NA NA NA NA
[3841] NA NA NA NA NA NA NA NA NA NA NA NA  2 NA NA  2 NA NA NA NA NA NA NA NA
[3865] NA NA NA NA NA NA NA NA  7 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[3889] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[3913] NA NA NA NA NA NA  3 NA NA NA  4 NA NA NA NA NA NA NA NA  6 NA NA NA NA
[3937] NA NA NA NA  7  6 NA  7 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[3961] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[3985] NA NA NA NA NA NA NA NA NA  4 NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[4009] NA NA NA NA NA NA NA NA NA NA NA NA NA NA  6 NA NA NA NA NA NA NA NA NA
[4033] NA  2 NA NA NA NA NA NA NA NA  6 NA NA NA NA NA  7 NA NA NA NA  4 NA NA
[4057] NA NA NA NA  1 NA NA NA NA NA NA NA NA NA NA NA  4 NA NA NA NA NA  7 NA
[4081]  4 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[4105] NA NA NA NA  2 NA NA NA NA NA NA NA  4 NA NA NA NA NA NA NA NA NA NA NA
[4129]  6 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[4153] NA  2 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[4177] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  6 NA NA NA NA NA NA
[4201] NA NA NA NA NA NA NA NA NA NA NA NA  6 NA NA NA  2 NA NA NA NA NA NA NA
[4225] NA NA NA NA NA NA NA NA NA  4 NA NA NA NA NA NA NA NA  7 NA NA NA NA NA
[4249] NA NA NA NA NA NA NA NA NA NA NA -1 NA NA  4 NA NA NA NA NA NA NA NA NA
[4273] NA NA  2 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  2 NA NA NA  6
[4297]  6 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  2
[4321] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[4345] NA  2 NA NA NA NA NA NA NA NA  7 NA NA NA NA NA  4 NA NA NA NA NA NA NA
[4369] NA NA NA NA NA NA NA NA NA NA  1 NA NA NA NA NA NA NA NA NA NA NA NA NA
[4393] NA NA NA NA NA NA NA NA NA NA NA  4 NA NA NA NA NA NA NA NA NA NA NA NA
[4417] NA NA NA NA NA NA NA NA NA NA NA  7 NA NA NA NA NA NA NA NA  5 NA NA NA
[4441] NA NA  6 NA NA NA NA NA NA NA NA NA NA  6 NA  7 NA NA NA NA NA NA NA NA
[4465] NA  4 NA NA NA NA NA NA NA NA NA NA NA NA  6 NA NA NA NA NA NA NA NA NA
[4489] NA NA NA NA NA NA  2 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[4513] NA NA  2 NA NA NA NA NA  5 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[4537] NA NA NA NA NA NA  2 NA NA NA  1 NA -1 NA NA NA NA NA  4  5 NA NA NA NA
[4561] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  2 NA NA NA NA NA NA
[4585] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  6  1
[4609] NA NA NA NA  2 NA NA NA  2  4 NA NA NA NA NA  1 NA NA NA NA NA NA NA NA
[4633]  2  6 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  5 NA NA
[4657] NA NA NA  4 NA NA NA NA NA NA NA NA NA NA NA NA  4 NA NA  2  4 NA NA NA
[4681] NA NA  4 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[4705] NA NA NA NA NA NA NA NA NA NA NA NA  7  1 NA NA NA NA NA NA NA NA NA NA
[4729] NA NA NA NA NA NA NA NA NA  4 NA NA NA  2 NA NA  4 NA NA NA NA  2 NA NA
[4753] NA NA NA NA  7 NA NA NA NA -1 NA NA NA NA NA NA NA  6 NA  1 NA NA  7 NA
[4777]  2 NA NA NA NA NA NA NA NA NA NA  1 NA NA NA NA NA NA NA NA NA NA NA NA
[4801] NA NA NA NA NA NA NA NA NA NA  4 NA NA NA NA NA NA  4 NA  7 NA  7 NA NA
[4825] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  6 NA NA
[4849] NA  2 NA NA NA NA NA NA NA NA NA NA NA NA  1 NA NA NA NA NA NA NA NA NA
[4873] NA  2 NA NA NA NA NA NA NA NA NA  4 NA  6 NA NA NA NA NA NA NA NA NA NA
[4897] NA NA NA NA  2 NA NA NA  6 NA NA  2 NA NA NA NA NA  5 NA NA NA NA NA NA
[4921] NA  7 NA NA  4 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[4945]  6 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  2 NA
[4969] NA NA NA NA NA NA  2 NA NA NA NA NA NA NA NA  6 NA NA  6 NA NA NA NA NA
[4993] NA NA NA NA NA NA  1 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[5017] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  2 NA NA NA NA NA
[5041] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  3 NA  4  3 NA NA
[5065] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[5089] NA NA NA NA NA NA  4 NA NA NA NA NA  4  4 NA NA NA NA  4 NA NA NA NA NA
[5113]  2 NA  4 NA NA NA NA NA NA NA NA NA NA NA NA NA  2 NA NA NA NA NA NA NA
[5137] NA NA NA NA  7 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[5161] NA NA NA NA NA  7 NA NA NA NA NA NA NA NA NA NA  7 NA NA NA  6 NA  6 NA
[5185] NA NA NA NA NA NA NA NA NA NA  6 NA  2 NA NA NA NA NA NA NA NA NA NA NA
[5209] NA NA  7 NA NA NA NA NA  4 NA NA NA NA NA  2 NA NA NA NA NA NA NA NA NA
[5233] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[5257] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  2 NA NA NA
[5281] NA NA NA NA NA  3 NA  2 NA  1 NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[5305] NA NA NA NA NA NA NA NA NA NA  2 NA NA NA NA NA NA NA NA NA NA NA NA NA
[5329] NA  7 NA NA NA NA NA NA  4 NA NA NA NA NA NA NA NA NA NA NA  3 NA NA  2
[5353] NA NA NA NA NA NA NA NA NA NA NA NA  3 NA  4 NA NA NA NA  2 NA NA NA NA
[5377] NA NA  4 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[5401] NA NA NA NA NA NA NA NA NA  4 NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[5425] NA NA  4  6 NA NA  7 NA NA NA NA NA NA NA NA NA  2 NA NA NA NA NA NA NA
[5449]  2 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[5473] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  6 NA NA NA NA  2 NA NA NA
[5497] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  4 NA NA NA NA NA NA
[5521] NA NA NA  7 NA NA NA NA NA NA NA NA NA NA NA  4 NA NA NA NA NA NA NA NA
[5545] NA NA NA NA  7 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  7 NA NA  7
[5569] NA  4 NA NA NA NA NA  6 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[5593] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  1 NA NA NA NA NA NA NA
[5617] NA  6 NA NA NA NA NA NA NA NA NA NA  6 NA NA NA NA NA NA NA NA NA NA NA
[5641] NA NA NA NA NA NA NA  2  7 NA NA NA NA NA NA NA NA  6 NA NA  2 NA NA NA
[5665] NA NA NA NA NA NA NA NA NA NA  5 NA NA NA NA NA NA NA NA NA NA NA NA NA
[5689] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  7  2 NA
[5713] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  4 NA NA NA
[5737] NA  4 NA NA NA  5 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  4  5 NA
[5761] NA NA  4 NA NA NA NA  2 NA  1 NA NA NA NA NA NA  4 NA NA NA NA NA NA NA
[5785] NA NA NA NA NA NA NA NA NA NA  3 NA NA NA NA NA NA NA NA  6 NA NA  7 NA
[5809] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  6 NA
[5833] NA NA NA NA

In [29]:
unique( voters$Q22 )

[1] NA  7  6  2 -1  1  4  5  3

In [30]:
voters$Q21

   [1]  1  1  1  1  1  2  1  1  1  2  1  1  2  1  3  1  1  1  1  1  2  1  1  1
  [25]  1  1  2  1  1  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1  1  1  1  2
  [49]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  2  3  1  1  1  1
  [73]  1  1  3  3  1  1  3  1  1  1  1  1  1  1  2  1  1  1  1  1  1  1  1  1
  [97]  2  1  3  1  1  2  2  3  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 [121]  1  1  1  1  1  1  1  1  1  3  1  1  1  2  3  3  1  1  1  1  1  1  1  2
 [145]  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1  1  1  1  1  2  1  1  1  1
 [169]  1  1  1  2  1  1  2  2  1  3  1  1  3  1  1  1  1  1  1  1  1  1  1  1
 [193]  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  3  3  2  1  1  1  1  1  1
 [217]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  3  1  1
 [241]  1  3  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1  1  1  1
 [265]  1  1  1  1  1  1  1  3  1  1  1 -1  3  1  1  1  1  1  1  1  1  1  1  2
 [289]  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  2  1  1  1  1  1
 [313]  1  1  1  1  1  1  1  1  1  2  1  1  1  3  1  1  3  1  1  1  1  1  1  1
 [337]  1  1  1  2  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  3  1  1
 [361]  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  2  1  1  1  1  1
 [385]  1  2  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  1  1  1  1  1
 [409]  1  1  3  1  1  1  1  2  1  1  1  1  1  2  1  1  2  1  1  1  1  1  1  1
 [433]  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  1  1  3  1  1
 [457]  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1  1
 [481]  2  1  1  1  1  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 [505]  1  3  1  1  1  1  1  1  1  1  3  1 -1  1  1  1  1  1  1  1  1  1  1  1
 [529]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 [553]  1  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1
 [577]  1  1  1  1  1  1  1  1 -1  1  1  1  1  1  3  1  1  1  1  1  1  1  1  1
 [601]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1
 [625]  1  1  1  1  3  1  1  2  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 [649]  3  1  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1  1  1  1  1  3  1  1
 [673]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 [697]  1  2  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  1  1  1
 [721]  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1  1
 [745]  1  1  1  1  1  2  3  1  1  1  1  1  1  3  1  1  1  1  1  1  1  1  3  3
 [769]  2  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  1  1  1  1  3  1  1  1
 [793]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1
 [817]  1  1  1  1  1  1  1  1  2  1  1  1  1  2  1  1  1  1  1  1  1  1  1  1
 [841]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 [865]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1
 [889]  1  2  1  1  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1  1  1  1  1  1
 [913]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1  1
 [937]  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  1  1  1  1  1  1  1
 [961]  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  1  1  1  1  1  1
 [985]  1  1  1  1  1  1  1  1  1  1  3  1  1  1  1  1  1  1  1  1  3  1  1  1
[1009]  1  1  1  2  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  2  1  1
[1033]  1  1  1  1  1  1  1  1  2  1  1  1  1  1  2  1  2  2  1  1  1  3  3  1
[1057]  1  1  1 -1  1  1  1  1  1  2  1  1  2  1 -1  1  1  3  1  1  1  1  2  1
[1081]  1  1  3  1  1  1  1  1  2  1  2  1  1  1  1  1  1  1  1  3  1  1  1  1
[1105]  1  1  1  1  1  2  2  1  1  1  1  1  1  1  1  3  1  1  1  1  1  1  1  1
[1129]  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  3  2  1  3  3  1  1  1
[1153]  1  3  1  1  1  1  1  1  1  3  1 -1  1  3  3  1  1  1  2  1  3  1  1  2
[1177]  1  3  1  3  1  1  1  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1  1  1
[1201]  1  1  1  1  1  1  2  2  1  2  2  2  1  1  1  1  1  1  1  1  1  1  1  1
[1225]  1  1  1  1  1  1  1  2  1  1  1  1  1  3  1  3  1  1  1  1  2  1  1  1
[1249]  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  1
[1273]  1  2  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2
[1297]  3  1  1  1  1  1  1  2  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1
[1321]  1  1  2  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  2  1  1  1  1
[1345]  1  3  1  1  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1  2  1  2  1  1
[1369]  1  3  1  1  2  3  1  1  1  1  2  1  1  1  1  1  1  1  1 -1  1  1  1  1
[1393]  1  1  1  1  1  2  1  1  1  1  2  1  1  1  1  1  1  1  1  1  1  1  3  2
[1417]  1  1  1  1  1  1  2  2  1  1  1  1  1  1  1  1  1  1  1 -1  1  1  1  1
[1441]  2  1  1  1  1  1  1  2  1  1  1  1  2  1  1  1  1  1 -1  1  1  1  2  1
[1465]  1  1  2  1  1  1  1  1 -1  1  1 -1  1  3  1  1  2  1  1  2  1  3  1  1
[1489]  1  1  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1  2  1  1  3  1  1  1
[1513]  1  1  3  1  1  1  3  1  1  2  3  3  1  1  3  1  1  1  1  1  1  1  1  1
[1537]  2  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[1561]  1  1  2  1  3  1  1  1  1  1  1  1  3  1  3  1  1  2  1  1  1  1  2  1
[1585]  1  1  1  2  1  1  3  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[1609]  2  1  2  1  1  1  1  2  1  3  1  1  2  1  3  1  1  1  1  3  1  1  1  1
[1633]  1  1  3  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  3
[1657]  2  3  1  1  1  1  2  1  3  1  1  1  1  1  1  1  3  1  1  1  1  2  1  1
[1681]  2  1  1  1  1  3  1  1  1  1  1  1  3  1  1  2  1  1  1  1  2  1  1  1
[1705]  1  1  1  1  2  1  1  1  1  1  1  1  1  1 -1  1  1  1  2  1  1  2  1  1
[1729]  1  1  1  2  1  1  1  1  1  1  1  1  2  1  3  1  1  1  1  1  1  1  1 -1
[1753]  1  1  2  1  2  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  1
[1777]  1  1  1  1  1  2  1  1  1  1  1  1  2  1  1  1  1  1  1  1  1  1  1  1
[1801]  1  1  1  1  1  3  1  1  1  1  1  3  1  1  1  1  1  2  1  1  1  3 -1  1
[1825]  1  1  1  1  1  1  1  2  1  1  1  1  1  1  3  1  1  2  1  1  1  1  1  1
[1849]  1  3  1  1  1  1  2  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[1873]  1  3  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[1897]  1  1  1  1  1  1  1  3  1  2  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[1921]  1  1  2  2  1  1  1  1  1  1  1  1  1  3  1  1  1  1  3  1  1  3  1  1
[1945]  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  3  1  1  3  1  1  1  1  1
[1969]  2  3  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  1  3  1
[1993]  1  2  1  1  1  1  3  1  3  1  1  1  1  1  1  1  2  1  1  1  1  3  1  1
[2017]  1  1  1  1  1  1  1  3  1  1  1  1  1  1  1  2  1  1  1  1  1  1  3  1
[2041]  1  1  1  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1  1  2  2  1  2  1
[2065]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1  2
[2089]  1  1  1  2  1  1  1  2  2  1  1  1  3  1  2  1  1  1  3  1  1  1  1  2
[2113]  2  1  1  1  1  1  1  1  1  2  1  1  1  2  1  1  1  1  1  1  1  1  1  1
[2137]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  1  3  2  1  3  1  1
[2161]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  3
[2185]  1  1  2  1  1  1  1  1  1  1  3  1  2  1  1  1  3  1  1  1  2  2  1  1
[2209]  1  1  1  1  1  2  1  1  1  1  1  1  1  1  1 -1  1  1  1  1  1  2  1  1
[2233]  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  3  3  3  1  1  1
[2257]  1  2  1  1  1  3  1  1  1  1  2  1  1  1  1  1  1  1  1  1  1  1  1  1
[2281]  3  1  1  1  1  1  2  1  1  1  1  2  1  1  1  1  1  1  1  1  1  1  1  2
[2305]  1  1  1  3  1  1  1  1  1  2  1  1  1  1  1  1  1  1  1  3  1  1  2  1
[2329]  1  1  1  1  2  2  1  1  1  1 -1  3  1  1  1  1  1  1  1  1  1  1  1  1
[2353]  1  2  2  1  1  1  1  1  1  1  3  1  1  1  1  1  1  2  1  1  2  1  3  1
[2377]  1  1  1  1  2  1  1  1  1  2  1  1  1  1  2  1  1  1  3  1  1  3  2  2
[2401]  1  1  1  1  1  1  1  1  1  1  3  1  1  1  3  1 -1  1  1  1  1  1  1  1
[2425]  1  1  1  2  1  1  1  1  1  1  3  1  1  1  1  3  1  1  1  1  1  1  1  1
[2449]  1  2  1  1  1  1  3  1  1  1  1  3  1  1  3  1  1  1  1  1  1  1  1  1
[2473]  2  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  1  1  1  1  1  3  1  2
[2497]  1  3  1  1  1  1  1  3  2  2  1  1  1  1  1  1  1  2  1  1  1  1  1  1
[2521]  1  1  1  1  1  2  1  1  1  1  1  1  2  2  2  1  1  2  1  1  1  1  1  1
[2545]  1  2  1  3  1  1  1  1  1  1  1  3  1  1  1  1  2  1  1  2  1  1  3  2
[2569]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[2593]  1  1  1  1  3  1  1  1  2  1  1  1  1  1  1  1  1  1  1  1  1  1  2  1
[2617]  2  1  1  1  3  3  1  2  2  1  1  1  1  1  1  1  1  3  1  1  1  2  2  1
[2641]  1  1  1  1  1  1  1  1  1  1  1 -1  3  1  1  1  1  1  1  1  1  1  1  1
[2665]  1  1  1  3  2  1  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1
[2689]  1  1  1  1  1  1  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[2713]  1  1  1  1  3  1  1  1  1  1  1  3  1  1  1  1  1  1  1  2  1  2  3  1
[2737]  1  3  1  1  2  1  1  2  1  3  1  1  1  1  3  3  1  1  1  3  1  1  1  1
[2761]  1  1  1  1  2  1  2  1  1  1  1  2  1  1  1  1  1  1  1  2  1  1  1  1
[2785]  1  1  1  2  1  2  1  1  1  1  1  3  1  1  1  1  1  3  1  1  1  3  1  1
[2809]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  3  1  1  1  2  1  1
[2833]  1  1  1  1  1  1  1  1  1  3  1  1  1  1  1  1  1  2  2  1  1  3  1  3
[2857]  1  1  2  1  1  1  1  1  1  1  1  1  1  1  2  2  1  1  3  1  1  1  1  1
[2881]  1  1  1  1  1  1  1  2  1  3  1  1  1  1  1  1  1  1  2  1  1  1  1  1
[2905]  2  1  1  1  1  1  2  3  1  1  1  2  1  1  1  2  3  1  2  1  1  1  2  1
[2929]  1  1  1  1  3  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  1  1
[2953]  1  1  3  1  1  1  1  1  1  3  1  1  1  1  1  1  1  1  3  1  1  1  1  2
[2977]  1  3  1  1  2  1  1  1  1  1  1 -1  1  1  1  1  1  1  1  1  1  1  3  1
[3001]  1  1  1  1  2  1  3  1  1  1  1  1  1  1  1  1  1  3  1  1  1  1  1  1
[3025]  1  1  1  1  2  1  1  1  1  1  3  3  1  3  1  1  1  1  2  1  1  1  1  1
[3049]  1  1  1  2  1  1  1  1  1  1  1  2  1  2  1  1  2  1  1  2  1  1  1  1
[3073]  1  1  1  2  1  1  3  1  1  1  1  1  1  2  1  1  1  1  1  1  1  1  3  1
[3097]  1  1  1  1  2  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  2  1  1  1
[3121]  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  2  1  1
[3145]  1  1  1  3  3  1  1  1  3  2  1  1  3  1  2  1  1  1  1  1  1  3  1  1
[3169]  1  1  1  1  1  2  1  2  1  1  1  2  1  1  2  1  2  1  1  1  3  1  1  1
[3193]  3  1  2  1  2  1  1  1  1  1  2  2  3  1  1  1  2  1  1  1  2  1  1  1
[3217]  1  1  1  1  1  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1  2  3  1  1
[3241]  1  1  1  1  1  1  1  1  1  1  1  1  3  1  3  1  1  1  1  1  1  2  2  1
[3265]  1  2  2  1  3  1  1  1  1  1  1  1  1  1  3  1  1  1  3  1  1  1  1  1
[3289]  1  3  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  1  3  1  1  1  1
[3313]  1  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1  2  2  2  1  1  1  1  1
[3337]  1  1  2  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  2  1
[3361]  1  1  1  1  2  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  1  1  1
[3385]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  3  1  3  1
[3409]  1  1  1  1  3  1  1  2  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  1
[3433]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[3457]  1  1  2  1  1  1  1  1  1  1  1  1  1  1  3  3  1  1  1  3  1  1  1  1
[3481]  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  1  3  1  1  1 -1
[3505]  1  3  1  1  1  3  1  1  2  3  1  1  1  1  1  1  1  1  1  1  1  1  3  1
[3529]  2  1  3  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1
[3553]  1  1  1  2  2  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1
[3577]  1  1  2  1  1  1  2  1  1  1  1  1  1  1  3  2  1  1  1  1  1  1  1  1
[3601]  1  3  1  1  1  1  1  1  1  1  3  1  1  1  1  3  1  1  1  1  1  2  1  1
[3625]  1  1  1  2  2  1  1  1  1  1  1  1  1  2  1  2  1  1  1  1  1  1  1  1
[3649]  1  3  1  1  1  1  1  1  3  1  2  1  1  1  1  1  3  2  1  1  1  1  1  2
[3673]  1  2  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  3  1  3  1  3
[3697]  1  1  1  1  1  2  1  1  1  1  1  1  1  1  1  1  2  1  1  3  2  1  3  1
[3721]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  1  1
[3745]  1  2  1  1  1  1  1  3  1  1  1  1  1  1  3  1  1  2  1  1  1  1  1  1
[3769]  3  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  1  1  1  1  1  1  1
[3793]  1  1  1  3  1  1  1  1  1  3  1  1  1  3  1  1  1  2  1  3  1  2  1  1
[3817]  2  1  1  1  1  1  1  1  3  1  2  1  3  1  1  2  1  1  1  1  2  1  1  1
[3841]  1  1  1  1  1  1  1  1  1  1  1  1  3  1  1  3  1  1  1  1  1  1  1  1
[3865]  1  1  1  1  1  1  1  1  2  1  1  1  1  3  1  1  1  1  1  1  1  1  1  1
[3889]  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1  1  1  3  1  3  1  1  1  1
[3913]  1  1  1  1  1  1  3  2  1  1  2  1  1  1  1  1  1  1  1  2  1  1  1  1
[3937]  1  1  1  1  2  3  1  2  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2
[3961]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1
[3985]  1  3  2  1  1  1  1  1  1  2  1  1  1  1  1  1  1  1  1  1  3  1  1  1
[4009]  1  1  1  1  1  1  1  1  1  3  1  1  1  1  2  1  1  1  1  1  1  1  1  1
[4033]  1  2  1  1  1  1  1  1  1  1  2  1  1  1  1  1  3  1  1  1  1  2  1  1
[4057]  1  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1  3  1  2  1
[4081]  2  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[4105]  1  1  3  1  3  1  1  1  1  1  1  1  2  1  1  1  1  1  3  1  1  1  1  1
[4129]  2  1  1  1  1  1  1  3  1  1  1  1  1  1  1  3  1  1  1  1  1  1  1  1
[4153]  1  3  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  3
[4177]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1
[4201]  1  1  1  1  2  1  1  1  1  1  1  1  2  1  1  1  3  1  1  1  1  1  1  1
[4225]  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  1  1  2  1  1  2  1  1
[4249]  3  1  1  1  1  1  1  1  1  1  1  2  1  1  2  1  1  1  1  1  1  1  1  1
[4273]  1  1  3  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  2
[4297]  2  1  1  1  3  1  2  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  3
[4321]  1  1  2  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[4345]  1  2  1  1  1  1  1  1  1  1  2  1  2  1  1  1  3  1  1  1  1  1  1  1
[4369]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[4393]  1  1  1  1  1  2  1  1  1  1  1  2  1  1  1  1  1  2  3  1  1  3  1  1
[4417]  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1  1  1  1  1  1  3  1  1  1
[4441]  1  1  2  1  1  1  2  1  1  1  1  1  1  3  1  2  1  1  1  1  1  1  1  1
[4465]  1  3  3  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  3  1  1  1  1
[4489]  1  1  1  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1  1  1
[4513]  1  2  2  1  1  1  1  1  2  1  3  1  1  1  1  1  1  1  3  1  1  1  3  2
[4537]  1  1  1  1  1  1  2  1  1  1  3  1  2  1  1  2  1  1  2  2  1  1  1  3
[4561]  1  1  1  1  1  1  1  1  1  1  1  1  1  3  1  1  3  3  1  1  1  1  1  1
[4585]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  3
[4609]  1  1  1  1  2  1  1  1  3  2  1  1  1  1  1  3  1  1  1  3  3  3  1  1
[4633]  2  2  1  3  1  1  1  1  3  3  1  1  1  3  1  1  1  1  1  1  1  3  1  1
[4657]  3  1  1  2  1  3  1  1  3  1  1  1  3  1  1  1  3  1  1  2  2  1  1  1
[4681]  1  1  2  1  1  1  3  1  1  1  2  3  1  1  1  1  1  1  1  1  1  1  1  1
[4705]  1  1  1  1  1  1  1  2  3  2  1  1  2  1  1  2  1  2  1  1  1  1  1  1
[4729]  1  1  1  1  1  1  1  1  1  2  1  2  1  2  1  1  2  1  3  1  1  2  1  1
[4753]  3  3  1  1  2  3  1  1  1  3  2  1  1  1  1  1  1  3  1  3  1  1  3  1
[4777]  2  1  1  3  1  1  1  1  1  1  1  2  1  1  1  1  1  1  1  1  1  2  2  1
[4801]  1  3  1  1  1  1  1  3  1  1  2  1  1  3  1  1  1  2  1  1  1  1  1  3
[4825]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1  1  2  1  1
[4849]  1  3  1  1  1  2  1  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1  3  1
[4873]  1  2  1  2  1  1  1  1  1  1  1  2  3  1  1  1  1  1  1  1  1  2  1  1
[4897]  1  1  1  1  2  1  3  1  3  1  1  3  1  1  1 -1  1  2  1  1  1  1  1  1
[4921]  3  2  2  1  2  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[4945]  2  1  1  1  1  1  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1  1  3  1
[4969]  1  3  1  1  1  1  3  1  1  1  1  1  1  1  1  2  1  1  3  1  1  1  1  1
[4993]  1  1  1  3  1  1  3  1  1  1  2  1  1  1  1  1  1  2  1  1  1  1  1  1
[5017]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1
[5041]  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  1  2  1  2  1  1  1
[5065]  1  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[5089]  1  1  1  1  1  1  3  1  2  1  1  1  3  2  3  1  1  1  1  1  1  3  1  1
[5113]  3  1  2  1  1  1  3  1  1  1  1  1  3  1  2  1  2  1  1  1  1  1  1  1
[5137]  1  1  1  1  2  1  1  2  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[5161]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1  3  1  2  1
[5185]  1  1  1  1  1  1  1  1  1  1  2  1  2  1  1  1  1  1  1  1  1  1  1  1
[5209]  1  1  1  1  1  1  1  1  3  1  1  1  1  1  3  1  1  1  1  1  1  1  1  1
[5233]  1  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1  1  2  1  1  1  1  1  1
[5257]  1  1  1  1  1  3  1  1  1  1  1  1  1  1  2  1  1  1  1  1  3  1  1  1
[5281]  1  1  1  1  1  2  1  2  1  3  1  1  1  3  1  1  3  1  1  1  1  1  1  1
[5305]  1  1  1  1  1  1  1  3  1  1  2  1  1  1  1  1  1  1  1  1  1  1  2  1
[5329]  1  2  1  1  1  1  1  1  2  1  1  1  1  1  1  1  3  1  1  1  2  1  1  3
[5353]  1  1  1  1  1  1  1  1  1  1  1  1  2  3  2  1  1  1  1  2  1  1  1  1
[5377]  1  1  2  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[5401]  1  1  1  1  1  1  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[5425]  1  1  2  2  1  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1  1  1  1  1
[5449]  3  3  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1
[5473]  1  1  1  3  1  1  1  1  1  3  1  1  1  1  1  2  1  1  2  1  3  1  1  1
[5497]  2  1  1  1  1  1  1  1  2  1  1  1  1  1  1  1  3  2  1  1  1  1  1  3
[5521]  1  1  1  2  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  1  1
[5545]  1  1  1  3  3  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1
[5569]  2  2  1  1  3  1  2  2  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1  3
[5593]  1  1  1  1  1  1  1  1  1  2  3  1  3  1  3  3  3  1  1  1  2  1  3  1
[5617]  1  2  1  1  1  1  1  1  1  1  3  1  2  1  1  1  3  1  1  1  1  2  1  1
[5641]  1  1  1  1  1  1  1  2  1  1  1  1  3  1  1  3  1  2  1  1  3  1  1  1
[5665]  1  1  1  3  1  1  1  1  1 -1  3  3  3  1  1  1  1  1  1  3  3  1  1  1
[5689]  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1  1  1  1  1  1  1  2  2  1
[5713]  1  1  1  1  1  1  1  1  1  1  1  1  1 -1  1  1  1  1  1  3  2  1  1  1
[5737]  1  2  1  1  1  2  1  1  1  1  3  1  1  3  1  1  1  1  3  1  1  3  3  1
[5761]  3  1  2  1  1  1  1  2  1  2  1  1  1  1  1  1  2  2  1  1  1  1  1  1
[5785]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  2  1
[5809]  1  1  1  3  1  3  1  1  1  2  1  1  1  1  1  1  2  1  1  1  1  1  3  1
[5833]  1  1  3  1

In [31]:
unique( voters$Q21 )

[1]  1  2  3 -1

In [35]:
factor( 
    voters$Q21,
    labels = c("?","Yes","No","Unsure")    
)

   [1] Yes    Yes    Yes    Yes    Yes    No     Yes    Yes    Yes    No
  [11] Yes    Yes    No     Yes    Unsure Yes    Yes    Yes    Yes    Yes
  [21] No     Yes    Yes    Yes    Yes    Yes    No     Yes    Yes    Yes
  [31] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
  [41] Unsure Yes    Yes    Yes    Yes    Yes    Yes    No     Yes    Yes
  [51] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
  [61] Yes    Yes    No     Yes    Yes    Yes    No     Unsure Yes    Yes
  [71] Yes    Yes    Yes    Yes    Unsure Unsure Yes    Yes    Unsure Yes
  [81] Yes    Yes    Yes    Yes    Yes    Yes    No     Yes    Yes    Yes
  [91] Yes    Yes    Yes    Yes    Yes    Yes    No     Yes    Unsure Yes
 [101] Yes    No     No     Unsure Yes    Yes    Yes    Yes    Yes    Yes
 [111] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [121] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Unsure
 [131] Yes    Yes    Yes    No     Unsure Unsure Yes    Yes    Yes    Yes
 [141] Yes    Yes    Yes    No     Yes    Yes    Yes    Yes    Yes    Yes
 [151] Yes    Yes    Yes    Yes    Yes    Unsure Yes    Yes    Yes    Yes
 [161] Yes    Yes    Yes    No     Yes    Yes    Yes    Yes    Yes    Yes
 [171] Yes    No     Yes    Yes    No     No     Yes    Unsure Yes    Yes
 [181] Unsure Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [191] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [201] No     Yes    Yes    Yes    Yes    Yes    Yes    Unsure Unsure No
 [211] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [221] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [231] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Unsure Yes    Yes
 [241] Yes    Unsure Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [251] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Unsure Yes    Yes
 [261] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [271] Yes    Unsure Yes    Yes    Yes    ?      Unsure Yes    Yes    Yes
 [281] Yes    Yes    Yes    Yes    Yes    Yes    Yes    No     Yes    Yes
 [291] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    No
 [301] Yes    Yes    Yes    Yes    Yes    Yes    No     Yes    Yes    Yes
 [311] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [321] Yes    No     Yes    Yes    Yes    Unsure Yes    Yes    Unsure Yes
 [331] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    No
 [341] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [351] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Unsure Yes    Yes
 [361] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [371] Yes    Yes    No     Yes    Yes    Yes    Yes    Yes    No     Yes
 [381] Yes    Yes    Yes    Yes    Yes    No     Yes    Yes    Yes    Yes
 [391] Yes    Yes    Yes    Yes    Yes    Yes    No     Yes    Yes    Yes
 [401] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [411] Unsure Yes    Yes    Yes    Yes    No     Yes    Yes    Yes    Yes
 [421] Yes    No     Yes    Yes    No     Yes    Yes    Yes    Yes    Yes
 [431] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [441] Yes    Yes    Yes    Yes    No     Yes    Yes    Yes    Yes    Yes
 [451] Yes    Yes    Yes    Unsure Yes    Yes    Yes    Yes    Yes    Yes
 [461] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Unsure Yes    Yes
 [471] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [481] No     Yes    Yes    Yes    Yes    Yes    Yes    Yes    Unsure Yes
 [491] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [501] Yes    Yes    Yes    Yes    Yes    Unsure Yes    Yes    Yes    Yes
 [511] Yes    Yes    Yes    Yes    Unsure Yes    ?      Yes    Yes    Yes
 [521] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [531] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [541] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [551] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [561] Yes    Yes    Yes    Yes    Unsure Yes    Yes    Yes    Yes    Yes
 [571] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [581] Yes    Yes    Yes    Yes    ?      Yes    Yes    Yes    Yes    Yes
 [591] Unsure Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [601] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [611] Yes    Yes    Yes    Yes    Yes    Yes    Yes    No     Yes    Yes
 [621] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Unsure Yes
 [631] Yes    No     Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [641] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Unsure Yes
 [651] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [661] Yes    Unsure Yes    Yes    Yes    Yes    Yes    Yes    Yes    Unsure
 [671] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [681] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [691] Yes    Yes    Yes    Yes    Yes    Yes    Yes    No     Yes    Yes
 [701] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [711] No     Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [721] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [731] Yes    Unsure Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [741] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    No
 [751] Unsure Yes    Yes    Yes    Yes    Yes    Yes    Unsure Yes    Yes
 [761] Yes    Yes    Yes    Yes    Yes    Yes    Unsure Unsure No     Yes
 [771] Yes    Yes    Yes    Yes    Yes    Yes    Yes    No     Yes    Yes
 [781] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Unsure Yes
 [791] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [801] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [811] Yes    Yes    No     Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [821] Yes    Yes    Yes    Yes    No     Yes    Yes    Yes    Yes    No
 [831] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [841] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [851] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [861] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [871] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [881] Yes    Yes    Yes    Yes    Yes    No     Yes    Yes    Yes    No
 [891] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [901] Yes    Yes    Yes    Unsure Yes    Yes    Yes    Yes    Yes    Yes
 [911] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [921] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [931] Yes    Unsure Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [941] Yes    Yes    Yes    Yes    Yes    Yes    No     Yes    Yes    Yes
 [951] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [961] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [971] Yes    No     Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [981] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
 [991] Yes    Yes    Yes    Yes    Unsure Yes    Yes    Yes    Yes    Yes
[1001] Yes    Yes    Yes    Yes    Unsure Yes    Yes    Yes    Yes    Yes
[1011] Yes    No     Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
[1021] Yes    Yes    No     Yes    Yes    Yes    Yes    Yes    Yes    No
[1031] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
[1041] No     Yes    Yes    Yes    Yes    Yes    No     Yes    No     No
[1051] Yes    Yes    Yes    Unsure Unsure Yes    Yes    Yes    Yes    ?
[1061] Yes    Yes    Yes    Yes    Yes    No     Yes    Yes    No     Yes
[1071] ?      Yes    Yes    Unsure Yes    Yes    Yes    Yes    No     Yes
[1081] Yes    Yes    Unsure Yes    Yes    Yes    Yes    Yes    No     Yes
[1091] No     Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Unsure
[1101] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    No
[1111] No     Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Unsure
[1121] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
[1131] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    No
[1141] Yes    Yes    Yes    Yes    Unsure No     Yes    Unsure Unsure Yes
[1151] Yes    Yes    Yes    Unsure Yes    Yes    Yes    Yes    Yes    Yes
[1161] Yes    Unsure Yes    ?      Yes    Unsure Unsure Yes    Yes    Yes
[1171] No     Yes    Unsure Yes    Yes    No     Yes    Unsure Yes    Unsure
[1181] Yes    Yes    Yes    Yes    Yes    Yes    Unsure Yes    Yes    Yes
[1191] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
[1201] Yes    Yes    Yes    Yes    Yes    Yes    No     No     Yes    No
[1211] No     No     Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
[1221] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
[1231] Yes    No     Yes    Yes    Yes    Yes    Yes    Unsure Yes    Unsure
[1241] Yes    Yes    Yes    Yes    No     Yes    Yes    Yes    Yes    Yes
[1251] Yes    Unsure Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
[1261] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
[1271] No     Yes    Yes    No     Yes    Yes    Yes    Yes    Yes    Yes
[1281] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
[1291] Yes    Yes    Yes    Yes    Yes    No     Unsure Yes    Yes    Yes
[1301] Yes    Yes    Yes    No     Yes    Yes    Yes    Yes    Yes    Yes
[1311] Yes    Yes    Yes    Yes    Yes    Yes    No     Yes    Yes    Yes
[1321] Yes    Yes    No     Yes    Yes    Yes    Yes    Yes    Yes    Yes
[1331] Yes    Yes    Yes    Yes    No     Yes    Yes    Yes    Yes    No
[1341] Yes    Yes    Yes    Yes    Yes    Unsure Yes    Yes    Yes    Yes
[1351] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Unsure
[1361] Yes    Yes    Yes    No     Yes    No     Yes    Yes    Yes    Unsure
[1371] Yes    Yes    No     Unsure Yes    Yes    Yes    Yes    No     Yes
[1381] Yes    Yes    Yes    Yes    Yes    Yes    Yes    ?      Yes    Yes
[1391] Yes    Yes    Yes    Yes    Yes    Yes    Yes    No     Yes    Yes
[1401] Yes    Yes    No     Yes    Yes    Yes    Yes    Yes    Yes    Yes
[1411] Yes    Yes    Yes    Yes    Unsure No     Yes    Yes    Yes    Yes
[1421] Yes    Yes    No     No     Yes    Yes    Yes    Yes    Yes    Yes
[1431] Yes    Yes    Yes    Yes    Yes    ?      Yes    Yes    Yes    Yes
[1441] No     Yes    Yes    Yes    Yes    Yes    Yes    No     Yes    Yes
[1451] Yes    Yes    No     Yes    Yes    Yes    Yes    Yes    ?      Yes
[1461] Yes    Yes    No     Yes    Yes    Yes    No     Yes    Yes    Yes
[1471] Yes    Yes    ?      Yes    Yes    ?      Yes    Unsure Yes    Yes
[1481] No     Yes    Yes    No     Yes    Unsure Yes    Yes    Yes    Yes
[1491] Yes    Yes    Yes    Unsure Yes    Yes    Yes    Yes    Yes    Yes
[1501] Yes    Yes    Yes    Yes    Yes    No     Yes    Yes    Unsure Yes
[1511] Yes    Yes    Yes    Yes    Unsure Yes    Yes    Yes    Unsure Yes
[1521] Yes    No     Unsure Unsure Yes    Yes    Unsure Yes    Yes    Yes
[1531] Yes    Yes    Yes    Yes    Yes    Yes    No     Yes    Yes    Yes
[1541] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
[1551] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
[1561] Yes    Yes    No     Yes    Unsure Yes    Yes    Yes    Yes    Yes
[1571] Yes    Yes    Unsure Yes    Unsure Yes    Yes    No     Yes    Yes
[1581] Yes    Yes    No     Yes    Yes    Yes    Yes    No     Yes    Yes
[1591] Unsure Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
[1601] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    No     Yes
[1611] No     Yes    Yes    Yes    Yes    No     Yes    Unsure Yes    Yes
[1621] No     Yes    Unsure Yes    Yes    Yes    Yes    Unsure Yes    Yes
[1631] Yes    Yes    Yes    Yes    Unsure Yes    Yes    Yes    Yes    Yes
[1641] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
[1651] Yes    Yes    Yes    Yes    Yes    Unsure No     Unsure Yes    Yes
[1661] Yes    Yes    No     Yes    Unsure Yes    Yes    Yes    Yes    Yes
[1671] Yes    Yes    Unsure Yes    Yes    Yes    Yes    No     Yes    Yes
[1681] No     Yes    Yes    Yes    Yes    Unsure Yes    Yes    Yes    Yes
[1691] Yes    Yes    Unsure Yes    Yes    No     Yes    Yes    Yes    Yes
[1701] No     Yes    Yes    Yes    Yes    Yes    Yes    Yes    No     Yes
[1711] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    ?      Yes
[1721] Yes    Yes    No     Yes    Yes    No     Yes    Yes    Yes    Yes
[1731] Yes    No     Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
[1741] No     Yes    Unsure Yes    Yes    Yes    Yes    Yes    Yes    Yes
[1751] Yes    ?      Yes    Yes    No     Yes    No     Yes    Yes    Yes
[1761] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
[1771] Yes    Yes    Yes    Yes    No     Yes    Yes    Yes    Yes    Yes
[1781] Yes    No     Yes    Yes    Yes    Yes    Yes    Yes    No     Yes
[1791] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
[1801] Yes    Yes    Yes    Yes    Yes    Unsure Yes    Yes    Yes    Yes
[1811] Yes    Unsure Yes    Yes    Yes    Yes    Yes    No     Yes    Yes
[1821] Yes    Unsure ?      Yes    Yes    Yes    Yes    Yes    Yes    Yes
[1831] Yes    No     Yes    Yes    Yes    Yes    Yes    Yes    Unsure Yes
[1841] Yes    No     Yes    Yes    Yes    Yes    Yes    Yes    Yes    Unsure
[1851] Yes    Yes    Yes    Yes    No     Yes    Yes    Yes    Yes    Yes
[1861] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
[1871] Yes    Yes    Yes    Unsure Yes    Yes    Yes    Unsure Yes    Yes
[1881] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
[1891] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
[1901] Yes    Yes    Yes    Unsure Yes    No     Yes    Yes    Yes    Yes
[1911] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
[1921] Yes    Yes    No     No     Yes    Yes    Yes    Yes    Yes    Yes
[1931] Yes    Yes    Yes    Unsure Yes    Yes    Yes    Yes    Unsure Yes
[1941] Yes    Unsure Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
[1951] Yes    Yes    Yes    No     Yes    Yes    Yes    Yes    Yes    Unsure
[1961] Yes    Yes    Unsure Yes    Yes    Yes    Yes    Yes    No     Unsure
[1971] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
[1981] Yes    Yes    No     Yes    Yes    Yes    Yes    Yes    Yes    Yes
[1991] Unsure Yes    Yes    No     Yes    Yes    Yes    Yes    Unsure Yes
[2001] Unsure Yes    Yes    Yes    Yes    Yes    Yes    Yes    No     Yes
[2011] Yes    Yes    Yes    Unsure Yes    Yes    Yes    Yes    Yes    Yes
[2021] Yes    Yes    Yes    Unsure Yes    Yes    Yes    Yes    Yes    Yes
[2031] Yes    No     Yes    Yes    Yes    Yes    Yes    Yes    Unsure Yes
[2041] Yes    Yes    Yes    Yes    Yes    Yes    Unsure Yes    Yes    Yes
[2051] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    No
[2061] No     Yes    No     Yes    Yes    Yes    Yes    Yes    Yes    Yes
[2071] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
[2081] Yes    Yes    Yes    Unsure Yes    Yes    Yes    No     Yes    Yes
[2091] Yes    No     Yes    Yes    Yes    No     No     Yes    Yes    Yes
[2101] Unsure Yes    No     Yes    Yes    Yes    Unsure Yes    Yes    Yes
[2111] Yes    No     No     Yes    Yes    Yes    Yes    Yes    Yes    Yes
[2121] Yes    No     Yes    Yes    Yes    No     Yes    Yes    Yes    Yes
[2131] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
[2141] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
[2151] Yes    Yes    No     Yes    Unsure No     Yes    Unsure Yes    Yes
[2161] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
[2171] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    No
[2181] Yes    Yes    Yes    Unsure Yes    Yes    No     Yes    Yes    Yes
[2191] Yes    Yes    Yes    Yes    Unsure Yes    No     Yes    Yes    Yes
[2201] Unsure Yes    Yes    Yes    No     No     Yes    Yes    Yes    Yes
[2211] Yes    Yes    Yes    No     Yes    Yes    Yes    Yes    Yes    Yes
[2221] Yes    Yes    Yes    ?      Yes    Yes    Yes    Yes    Yes    No
[2231] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
[2241] Yes    Yes    Yes    Yes    No     Yes    Yes    Yes    Yes    Yes
[2251] Unsure Unsure Unsure Yes    Yes    Yes    Yes    No     Yes    Yes
[2261] Yes    Unsure Yes    Yes    Yes    Yes    No     Yes    Yes    Yes
[2271] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
[2281] Unsure Yes    Yes    Yes    Yes    Yes    No     Yes    Yes    Yes
[2291] Yes    No     Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
[2301] Yes    Yes    Yes    No     Yes    Yes    Yes    Unsure Yes    Yes
[2311] Yes    Yes    Yes    No     Yes    Yes    Yes    Yes    Yes    Yes
[2321] Yes    Yes    Yes    Unsure Yes    Yes    No     Yes    Yes    Yes
[2331] Yes    Yes    No     No     Yes    Yes    Yes    Yes    ?      Unsure
[2341] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
[2351] Yes    Yes    Yes    No     No     Yes    Yes    Yes    Yes    Yes
[2361] Yes    Yes    Unsure Yes    Yes    Yes    Yes    Yes    Yes    No
[2371] Yes    Yes    No     Yes    Unsure Yes    Yes    Yes    Yes    Yes
[2381] No     Yes    Yes    Yes    Yes    No     Yes    Yes    Yes    Yes
[2391] No     Yes    Yes    Yes    Unsure Yes    Yes    Unsure No     No
[2401] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
[2411] Unsure Yes    Yes    Yes    Unsure Yes    ?      Yes    Yes    Yes
[2421] Yes    Yes    Yes    Yes    Yes    Yes    Yes    No     Yes    Yes
[2431] Yes    Yes    Yes    Yes    Unsure Yes    Yes    Yes    Yes    Unsure
[2441] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    No
[2451] Yes    Yes    Yes    Yes    Unsure Yes    Yes    Yes    Yes    Unsure
[2461] Yes    Yes    Unsure Yes    Yes    Yes    Yes    Yes    Yes    Yes
[2471] Yes    Yes    No     Yes    Yes    Yes    Yes    Yes    Yes    Yes
[2481] Yes    No     Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
[2491] Yes    Yes    Yes    Unsure Yes    No     Yes    Unsure Yes    Yes
[2501] Yes    Yes    Yes    Unsure No     No     Yes    Yes    Yes    Yes
[2511] Yes    Yes    Yes    No     Yes    Yes    Yes    Yes    Yes    Yes
[2521] Yes    Yes    Yes    Yes    Yes    No     Yes    Yes    Yes    Yes
[2531] Yes    Yes    No     No     No     Yes    Yes    No     Yes    Yes
[2541] Yes    Yes    Yes    Yes    Yes    No     Yes    Unsure Yes    Yes
[2551] Yes    Yes    Yes    Yes    Yes    Unsure Yes    Yes    Yes    Yes
[2561] No     Yes    Yes    No     Yes    Yes    Unsure No     Yes    Yes
[2571] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
[2581] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
[2591] Yes    Yes    Yes    Yes    Yes    Yes    Unsure Yes    Yes    Yes
[2601] No     Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
[2611] Yes    Yes    Yes    Yes    No     Yes    No     Yes    Yes    Yes
[2621] Unsure Unsure Yes    No     No     Yes    Yes    Yes    Yes    Yes
[2631] Yes    Yes    Yes    Unsure Yes    Yes    Yes    No     No     Yes
[2641] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
[2651] Yes    ?      Unsure Yes    Yes    Yes    Yes    Yes    Yes    Yes
[2661] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Unsure No     Yes
[2671] Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes    Yes
[2681] Yes    Yes    No     Yes    Yes    Yes    Yes    Yes    Yes    Yes

In [33]:
voters$Q21

   [1]  1  1  1  1  1  2  1  1  1  2  1  1  2  1  3  1  1  1  1  1  2  1  1  1
  [25]  1  1  2  1  1  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1  1  1  1  2
  [49]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  2  3  1  1  1  1
  [73]  1  1  3  3  1  1  3  1  1  1  1  1  1  1  2  1  1  1  1  1  1  1  1  1
  [97]  2  1  3  1  1  2  2  3  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 [121]  1  1  1  1  1  1  1  1  1  3  1  1  1  2  3  3  1  1  1  1  1  1  1  2
 [145]  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1  1  1  1  1  2  1  1  1  1
 [169]  1  1  1  2  1  1  2  2  1  3  1  1  3  1  1  1  1  1  1  1  1  1  1  1
 [193]  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  3  3  2  1  1  1  1  1  1
 [217]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  3  1  1
 [241]  1  3  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1  1  1  1
 [265]  1  1  1  1  1  1  1  3  1  1  1 -1  3  1  1  1  1  1  1  1  1  1  1  2
 [289]  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  2  1  1  1  1  1
 [313]  1  1  1  1  1  1  1  1  1  2  1  1  1  3  1  1  3  1  1  1  1  1  1  1
 [337]  1  1  1  2  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  3  1  1
 [361]  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  2  1  1  1  1  1
 [385]  1  2  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  1  1  1  1  1
 [409]  1  1  3  1  1  1  1  2  1  1  1  1  1  2  1  1  2  1  1  1  1  1  1  1
 [433]  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  1  1  3  1  1
 [457]  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1  1
 [481]  2  1  1  1  1  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 [505]  1  3  1  1  1  1  1  1  1  1  3  1 -1  1  1  1  1  1  1  1  1  1  1  1
 [529]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 [553]  1  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1
 [577]  1  1  1  1  1  1  1  1 -1  1  1  1  1  1  3  1  1  1  1  1  1  1  1  1
 [601]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1
 [625]  1  1  1  1  3  1  1  2  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 [649]  3  1  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1  1  1  1  1  3  1  1
 [673]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 [697]  1  2  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  1  1  1
 [721]  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1  1
 [745]  1  1  1  1  1  2  3  1  1  1  1  1  1  3  1  1  1  1  1  1  1  1  3  3
 [769]  2  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  1  1  1  1  3  1  1  1
 [793]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1
 [817]  1  1  1  1  1  1  1  1  2  1  1  1  1  2  1  1  1  1  1  1  1  1  1  1
 [841]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 [865]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1
 [889]  1  2  1  1  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1  1  1  1  1  1
 [913]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1  1
 [937]  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  1  1  1  1  1  1  1
 [961]  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  1  1  1  1  1  1
 [985]  1  1  1  1  1  1  1  1  1  1  3  1  1  1  1  1  1  1  1  1  3  1  1  1
[1009]  1  1  1  2  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  2  1  1
[1033]  1  1  1  1  1  1  1  1  2  1  1  1  1  1  2  1  2  2  1  1  1  3  3  1
[1057]  1  1  1 -1  1  1  1  1  1  2  1  1  2  1 -1  1  1  3  1  1  1  1  2  1
[1081]  1  1  3  1  1  1  1  1  2  1  2  1  1  1  1  1  1  1  1  3  1  1  1  1
[1105]  1  1  1  1  1  2  2  1  1  1  1  1  1  1  1  3  1  1  1  1  1  1  1  1
[1129]  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  3  2  1  3  3  1  1  1
[1153]  1  3  1  1  1  1  1  1  1  3  1 -1  1  3  3  1  1  1  2  1  3  1  1  2
[1177]  1  3  1  3  1  1  1  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1  1  1
[1201]  1  1  1  1  1  1  2  2  1  2  2  2  1  1  1  1  1  1  1  1  1  1  1  1
[1225]  1  1  1  1  1  1  1  2  1  1  1  1  1  3  1  3  1  1  1  1  2  1  1  1
[1249]  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  1
[1273]  1  2  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2
[1297]  3  1  1  1  1  1  1  2  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1
[1321]  1  1  2  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  2  1  1  1  1
[1345]  1  3  1  1  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1  2  1  2  1  1
[1369]  1  3  1  1  2  3  1  1  1  1  2  1  1  1  1  1  1  1  1 -1  1  1  1  1
[1393]  1  1  1  1  1  2  1  1  1  1  2  1  1  1  1  1  1  1  1  1  1  1  3  2
[1417]  1  1  1  1  1  1  2  2  1  1  1  1  1  1  1  1  1  1  1 -1  1  1  1  1
[1441]  2  1  1  1  1  1  1  2  1  1  1  1  2  1  1  1  1  1 -1  1  1  1  2  1
[1465]  1  1  2  1  1  1  1  1 -1  1  1 -1  1  3  1  1  2  1  1  2  1  3  1  1
[1489]  1  1  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1  2  1  1  3  1  1  1
[1513]  1  1  3  1  1  1  3  1  1  2  3  3  1  1  3  1  1  1  1  1  1  1  1  1
[1537]  2  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[1561]  1  1  2  1  3  1  1  1  1  1  1  1  3  1  3  1  1  2  1  1  1  1  2  1
[1585]  1  1  1  2  1  1  3  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[1609]  2  1  2  1  1  1  1  2  1  3  1  1  2  1  3  1  1  1  1  3  1  1  1  1
[1633]  1  1  3  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  3
[1657]  2  3  1  1  1  1  2  1  3  1  1  1  1  1  1  1  3  1  1  1  1  2  1  1
[1681]  2  1  1  1  1  3  1  1  1  1  1  1  3  1  1  2  1  1  1  1  2  1  1  1
[1705]  1  1  1  1  2  1  1  1  1  1  1  1  1  1 -1  1  1  1  2  1  1  2  1  1
[1729]  1  1  1  2  1  1  1  1  1  1  1  1  2  1  3  1  1  1  1  1  1  1  1 -1
[1753]  1  1  2  1  2  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  1
[1777]  1  1  1  1  1  2  1  1  1  1  1  1  2  1  1  1  1  1  1  1  1  1  1  1
[1801]  1  1  1  1  1  3  1  1  1  1  1  3  1  1  1  1  1  2  1  1  1  3 -1  1
[1825]  1  1  1  1  1  1  1  2  1  1  1  1  1  1  3  1  1  2  1  1  1  1  1  1
[1849]  1  3  1  1  1  1  2  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[1873]  1  3  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[1897]  1  1  1  1  1  1  1  3  1  2  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[1921]  1  1  2  2  1  1  1  1  1  1  1  1  1  3  1  1  1  1  3  1  1  3  1  1
[1945]  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  3  1  1  3  1  1  1  1  1
[1969]  2  3  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  1  3  1
[1993]  1  2  1  1  1  1  3  1  3  1  1  1  1  1  1  1  2  1  1  1  1  3  1  1
[2017]  1  1  1  1  1  1  1  3  1  1  1  1  1  1  1  2  1  1  1  1  1  1  3  1
[2041]  1  1  1  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1  1  2  2  1  2  1
[2065]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1  2
[2089]  1  1  1  2  1  1  1  2  2  1  1  1  3  1  2  1  1  1  3  1  1  1  1  2
[2113]  2  1  1  1  1  1  1  1  1  2  1  1  1  2  1  1  1  1  1  1  1  1  1  1
[2137]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  1  3  2  1  3  1  1
[2161]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  3
[2185]  1  1  2  1  1  1  1  1  1  1  3  1  2  1  1  1  3  1  1  1  2  2  1  1
[2209]  1  1  1  1  1  2  1  1  1  1  1  1  1  1  1 -1  1  1  1  1  1  2  1  1
[2233]  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  3  3  3  1  1  1
[2257]  1  2  1  1  1  3  1  1  1  1  2  1  1  1  1  1  1  1  1  1  1  1  1  1
[2281]  3  1  1  1  1  1  2  1  1  1  1  2  1  1  1  1  1  1  1  1  1  1  1  2
[2305]  1  1  1  3  1  1  1  1  1  2  1  1  1  1  1  1  1  1  1  3  1  1  2  1
[2329]  1  1  1  1  2  2  1  1  1  1 -1  3  1  1  1  1  1  1  1  1  1  1  1  1
[2353]  1  2  2  1  1  1  1  1  1  1  3  1  1  1  1  1  1  2  1  1  2  1  3  1
[2377]  1  1  1  1  2  1  1  1  1  2  1  1  1  1  2  1  1  1  3  1  1  3  2  2
[2401]  1  1  1  1  1  1  1  1  1  1  3  1  1  1  3  1 -1  1  1  1  1  1  1  1
[2425]  1  1  1  2  1  1  1  1  1  1  3  1  1  1  1  3  1  1  1  1  1  1  1  1
[2449]  1  2  1  1  1  1  3  1  1  1  1  3  1  1  3  1  1  1  1  1  1  1  1  1
[2473]  2  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  1  1  1  1  1  3  1  2
[2497]  1  3  1  1  1  1  1  3  2  2  1  1  1  1  1  1  1  2  1  1  1  1  1  1
[2521]  1  1  1  1  1  2  1  1  1  1  1  1  2  2  2  1  1  2  1  1  1  1  1  1
[2545]  1  2  1  3  1  1  1  1  1  1  1  3  1  1  1  1  2  1  1  2  1  1  3  2
[2569]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[2593]  1  1  1  1  3  1  1  1  2  1  1  1  1  1  1  1  1  1  1  1  1  1  2  1
[2617]  2  1  1  1  3  3  1  2  2  1  1  1  1  1  1  1  1  3  1  1  1  2  2  1
[2641]  1  1  1  1  1  1  1  1  1  1  1 -1  3  1  1  1  1  1  1  1  1  1  1  1
[2665]  1  1  1  3  2  1  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1
[2689]  1  1  1  1  1  1  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[2713]  1  1  1  1  3  1  1  1  1  1  1  3  1  1  1  1  1  1  1  2  1  2  3  1
[2737]  1  3  1  1  2  1  1  2  1  3  1  1  1  1  3  3  1  1  1  3  1  1  1  1
[2761]  1  1  1  1  2  1  2  1  1  1  1  2  1  1  1  1  1  1  1  2  1  1  1  1
[2785]  1  1  1  2  1  2  1  1  1  1  1  3  1  1  1  1  1  3  1  1  1  3  1  1
[2809]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  3  1  1  1  2  1  1
[2833]  1  1  1  1  1  1  1  1  1  3  1  1  1  1  1  1  1  2  2  1  1  3  1  3
[2857]  1  1  2  1  1  1  1  1  1  1  1  1  1  1  2  2  1  1  3  1  1  1  1  1
[2881]  1  1  1  1  1  1  1  2  1  3  1  1  1  1  1  1  1  1  2  1  1  1  1  1
[2905]  2  1  1  1  1  1  2  3  1  1  1  2  1  1  1  2  3  1  2  1  1  1  2  1
[2929]  1  1  1  1  3  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  1  1
[2953]  1  1  3  1  1  1  1  1  1  3  1  1  1  1  1  1  1  1  3  1  1  1  1  2
[2977]  1  3  1  1  2  1  1  1  1  1  1 -1  1  1  1  1  1  1  1  1  1  1  3  1
[3001]  1  1  1  1  2  1  3  1  1  1  1  1  1  1  1  1  1  3  1  1  1  1  1  1
[3025]  1  1  1  1  2  1  1  1  1  1  3  3  1  3  1  1  1  1  2  1  1  1  1  1
[3049]  1  1  1  2  1  1  1  1  1  1  1  2  1  2  1  1  2  1  1  2  1  1  1  1
[3073]  1  1  1  2  1  1  3  1  1  1  1  1  1  2  1  1  1  1  1  1  1  1  3  1
[3097]  1  1  1  1  2  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  2  1  1  1
[3121]  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  2  1  1
[3145]  1  1  1  3  3  1  1  1  3  2  1  1  3  1  2  1  1  1  1  1  1  3  1  1
[3169]  1  1  1  1  1  2  1  2  1  1  1  2  1  1  2  1  2  1  1  1  3  1  1  1
[3193]  3  1  2  1  2  1  1  1  1  1  2  2  3  1  1  1  2  1  1  1  2  1  1  1
[3217]  1  1  1  1  1  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1  2  3  1  1
[3241]  1  1  1  1  1  1  1  1  1  1  1  1  3  1  3  1  1  1  1  1  1  2  2  1
[3265]  1  2  2  1  3  1  1  1  1  1  1  1  1  1  3  1  1  1  3  1  1  1  1  1
[3289]  1  3  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  1  3  1  1  1  1
[3313]  1  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1  2  2  2  1  1  1  1  1
[3337]  1  1  2  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  2  1
[3361]  1  1  1  1  2  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  1  1  1
[3385]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  3  1  3  1
[3409]  1  1  1  1  3  1  1  2  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  1
[3433]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[3457]  1  1  2  1  1  1  1  1  1  1  1  1  1  1  3  3  1  1  1  3  1  1  1  1
[3481]  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  1  3  1  1  1 -1
[3505]  1  3  1  1  1  3  1  1  2  3  1  1  1  1  1  1  1  1  1  1  1  1  3  1
[3529]  2  1  3  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1
[3553]  1  1  1  2  2  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1
[3577]  1  1  2  1  1  1  2  1  1  1  1  1  1  1  3  2  1  1  1  1  1  1  1  1
[3601]  1  3  1  1  1  1  1  1  1  1  3  1  1  1  1  3  1  1  1  1  1  2  1  1
[3625]  1  1  1  2  2  1  1  1  1  1  1  1  1  2  1  2  1  1  1  1  1  1  1  1
[3649]  1  3  1  1  1  1  1  1  3  1  2  1  1  1  1  1  3  2  1  1  1  1  1  2
[3673]  1  2  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  3  1  3  1  3
[3697]  1  1  1  1  1  2  1  1  1  1  1  1  1  1  1  1  2  1  1  3  2  1  3  1
[3721]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  1  1
[3745]  1  2  1  1  1  1  1  3  1  1  1  1  1  1  3  1  1  2  1  1  1  1  1  1
[3769]  3  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  1  1  1  1  1  1  1
[3793]  1  1  1  3  1  1  1  1  1  3  1  1  1  3  1  1  1  2  1  3  1  2  1  1
[3817]  2  1  1  1  1  1  1  1  3  1  2  1  3  1  1  2  1  1  1  1  2  1  1  1
[3841]  1  1  1  1  1  1  1  1  1  1  1  1  3  1  1  3  1  1  1  1  1  1  1  1
[3865]  1  1  1  1  1  1  1  1  2  1  1  1  1  3  1  1  1  1  1  1  1  1  1  1
[3889]  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1  1  1  3  1  3  1  1  1  1
[3913]  1  1  1  1  1  1  3  2  1  1  2  1  1  1  1  1  1  1  1  2  1  1  1  1
[3937]  1  1  1  1  2  3  1  2  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2
[3961]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1
[3985]  1  3  2  1  1  1  1  1  1  2  1  1  1  1  1  1  1  1  1  1  3  1  1  1
[4009]  1  1  1  1  1  1  1  1  1  3  1  1  1  1  2  1  1  1  1  1  1  1  1  1
[4033]  1  2  1  1  1  1  1  1  1  1  2  1  1  1  1  1  3  1  1  1  1  2  1  1
[4057]  1  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1  3  1  2  1
[4081]  2  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[4105]  1  1  3  1  3  1  1  1  1  1  1  1  2  1  1  1  1  1  3  1  1  1  1  1
[4129]  2  1  1  1  1  1  1  3  1  1  1  1  1  1  1  3  1  1  1  1  1  1  1  1
[4153]  1  3  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  3
[4177]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1
[4201]  1  1  1  1  2  1  1  1  1  1  1  1  2  1  1  1  3  1  1  1  1  1  1  1
[4225]  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  1  1  2  1  1  2  1  1
[4249]  3  1  1  1  1  1  1  1  1  1  1  2  1  1  2  1  1  1  1  1  1  1  1  1
[4273]  1  1  3  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  2
[4297]  2  1  1  1  3  1  2  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  3
[4321]  1  1  2  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[4345]  1  2  1  1  1  1  1  1  1  1  2  1  2  1  1  1  3  1  1  1  1  1  1  1
[4369]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[4393]  1  1  1  1  1  2  1  1  1  1  1  2  1  1  1  1  1  2  3  1  1  3  1  1
[4417]  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1  1  1  1  1  1  3  1  1  1
[4441]  1  1  2  1  1  1  2  1  1  1  1  1  1  3  1  2  1  1  1  1  1  1  1  1
[4465]  1  3  3  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  3  1  1  1  1
[4489]  1  1  1  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1  1  1
[4513]  1  2  2  1  1  1  1  1  2  1  3  1  1  1  1  1  1  1  3  1  1  1  3  2
[4537]  1  1  1  1  1  1  2  1  1  1  3  1  2  1  1  2  1  1  2  2  1  1  1  3
[4561]  1  1  1  1  1  1  1  1  1  1  1  1  1  3  1  1  3  3  1  1  1  1  1  1
[4585]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  3
[4609]  1  1  1  1  2  1  1  1  3  2  1  1  1  1  1  3  1  1  1  3  3  3  1  1
[4633]  2  2  1  3  1  1  1  1  3  3  1  1  1  3  1  1  1  1  1  1  1  3  1  1
[4657]  3  1  1  2  1  3  1  1  3  1  1  1  3  1  1  1  3  1  1  2  2  1  1  1
[4681]  1  1  2  1  1  1  3  1  1  1  2  3  1  1  1  1  1  1  1  1  1  1  1  1
[4705]  1  1  1  1  1  1  1  2  3  2  1  1  2  1  1  2  1  2  1  1  1  1  1  1
[4729]  1  1  1  1  1  1  1  1  1  2  1  2  1  2  1  1  2  1  3  1  1  2  1  1
[4753]  3  3  1  1  2  3  1  1  1  3  2  1  1  1  1  1  1  3  1  3  1  1  3  1
[4777]  2  1  1  3  1  1  1  1  1  1  1  2  1  1  1  1  1  1  1  1  1  2  2  1
[4801]  1  3  1  1  1  1  1  3  1  1  2  1  1  3  1  1  1  2  1  1  1  1  1  3
[4825]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1  1  2  1  1
[4849]  1  3  1  1  1  2  1  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1  3  1
[4873]  1  2  1  2  1  1  1  1  1  1  1  2  3  1  1  1  1  1  1  1  1  2  1  1
[4897]  1  1  1  1  2  1  3  1  3  1  1  3  1  1  1 -1  1  2  1  1  1  1  1  1
[4921]  3  2  2  1  2  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[4945]  2  1  1  1  1  1  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1  1  3  1
[4969]  1  3  1  1  1  1  3  1  1  1  1  1  1  1  1  2  1  1  3  1  1  1  1  1
[4993]  1  1  1  3  1  1  3  1  1  1  2  1  1  1  1  1  1  2  1  1  1  1  1  1
[5017]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1
[5041]  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  1  2  1  2  1  1  1
[5065]  1  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[5089]  1  1  1  1  1  1  3  1  2  1  1  1  3  2  3  1  1  1  1  1  1  3  1  1
[5113]  3  1  2  1  1  1  3  1  1  1  1  1  3  1  2  1  2  1  1  1  1  1  1  1
[5137]  1  1  1  1  2  1  1  2  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[5161]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1  3  1  2  1
[5185]  1  1  1  1  1  1  1  1  1  1  2  1  2  1  1  1  1  1  1  1  1  1  1  1
[5209]  1  1  1  1  1  1  1  1  3  1  1  1  1  1  3  1  1  1  1  1  1  1  1  1
[5233]  1  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1  1  2  1  1  1  1  1  1
[5257]  1  1  1  1  1  3  1  1  1  1  1  1  1  1  2  1  1  1  1  1  3  1  1  1
[5281]  1  1  1  1  1  2  1  2  1  3  1  1  1  3  1  1  3  1  1  1  1  1  1  1
[5305]  1  1  1  1  1  1  1  3  1  1  2  1  1  1  1  1  1  1  1  1  1  1  2  1
[5329]  1  2  1  1  1  1  1  1  2  1  1  1  1  1  1  1  3  1  1  1  2  1  1  3
[5353]  1  1  1  1  1  1  1  1  1  1  1  1  2  3  2  1  1  1  1  2  1  1  1  1
[5377]  1  1  2  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[5401]  1  1  1  1  1  1  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1  1  1  1
[5425]  1  1  2  2  1  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1  1  1  1  1
[5449]  3  3  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1
[5473]  1  1  1  3  1  1  1  1  1  3  1  1  1  1  1  2  1  1  2  1  3  1  1  1
[5497]  2  1  1  1  1  1  1  1  2  1  1  1  1  1  1  1  3  2  1  1  1  1  1  3
[5521]  1  1  1  2  1  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1  1  1
[5545]  1  1  1  3  3  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1
[5569]  2  2  1  1  3  1  2  2  1  1  1  3  1  1  1  1  1  1  1  1  1  1  1  3
[5593]  1  1  1  1  1  1  1  1  1  2  3  1  3  1  3  3  3  1  1  1  2  1  3  1
[5617]  1  2  1  1  1  1  1  1  1  1  3  1  2  1  1  1  3  1  1  1  1  2  1  1
[5641]  1  1  1  1  1  1  1  2  1  1  1  1  3  1  1  3  1  2  1  1  3  1  1  1
[5665]  1  1  1  3  1  1  1  1  1 -1  3  3  3  1  1  1  1  1  1  3  3  1  1  1
[5689]  1  1  1  1  1  1  1  1  1  1  1  3  1  1  1  1  1  1  1  1  1  2  2  1
[5713]  1  1  1  1  1  1  1  1  1  1  1  1  1 -1  1  1  1  1  1  3  2  1  1  1
[5737]  1  2  1  1  1  2  1  1  1  1  3  1  1  3  1  1  1  1  3  1  1  3  3  1
[5761]  3  1  2  1  1  1  1  2  1  2  1  1  1  1  1  1  2  2  1  1  1  1  1  1
[5785]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  1  1  2  1
[5809]  1  1  1  3  1  3  1  1  1  2  1  1  1  1  1  1  2  1  1  1  1  1  3  1
[5833]  1  1  3  1

In [ ]:
?factor

In [38]:
temps <- 1:31

In [39]:
mean(temps)

[1] 16

In [40]:
var1 <- sample(1:100,15)

In [41]:
var1

 [1]  11  86  16  46  99  96  83  28  30  40  26  13 100  92   8

In [42]:
var1[2]

[1] 86

In [43]:
var1[1:4]

[1] 11 86 16 46

In [44]:
var1[c(1,5,8)]

[1] 11 99 28

In [45]:
var1[-c(1,5,8)]

 [1]  86  16  46  96  83  30  40  26  13 100  92   8

In [47]:
var1 < 50

 [1]  TRUE FALSE  TRUE  TRUE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE
[13] FALSE FALSE  TRUE

In [49]:
var1[ var1 < 50 ]

[1] 11 16 46 28 30 40 26 13  8

In [50]:
which( var1 < 50 )

[1]  1  3  4  8  9 10 11 12 15